Login via email address or username for OpenID
OrchardCMS/OrchardCore pull request #10304
Opened 2021-09-19 11:16 UTC by deanmarcussen

Fixes https://github.com/OrchardCMS/OrchardCore/issues/10190

2021-09-20 15:09 UTC, kevinchalet commented
IIRC, the login controller - that doesn't call this method - does additional checks like ensuring "local logins" are allowed. Is it something the user service should do too?

2021-09-20 16:58 UTC, deanmarcussen commented
You’re probably right @kevinchalet I suspect it may not even check if the user is disabled.

2022-11-28 15:52 UTC, wAsnk commented
Could this be merged? This bug still persists.

2022-11-28 19:13 UTC, Skrypt commented
@deanmarcussen Is it still something that we should merge?

2022-11-29 09:06 UTC, deanmarcussen commented
See comments from @kevinchalet - while this fixes one issue, it is not complete (at a glance)

2022-11-29 09:16 UTC, wAsnk commented
> See comments from @kevinchalet - while this fixes one issue, it is not complete (at a glance)

While it is not complete it still fixes one bug.

2022-11-29 09:20 UTC, deanmarcussen commented
You are welcome to fork it, and fix the remaining :)

2023-03-14 14:53 UTC, Piedone requested changes

2023-03-14 14:53 UTC, Piedone commented on src/OrchardCore/OrchardCore.Users.Core/Services/UserService.cs
> +            var user = await _userManager.FindByNameAsync(userName) ?? await _userManager.FindByEmailAsync(userName);
Include this logic in `GetUserAsync()` instead and then:

```suggestion
            var user = await GetUserAsync(userName);
```

2023-06-14 17:45 UTC, closed without merging