Fix the BUG that CorrelationId is overwritten
OrchardCMS/OrchardCore pull request #10928
Opened 2021-12-28 10:56 UTC by hyzx86

A Token will be generated at signal 2 based on the current correlation ID
And then create the content
But once the content is created, the code again assigns values to the associated IDS of the workflow
Causes 3 and 4 never to trigger

![image](https://user-images.githubusercontent.com/15613121/147559086-c42ad89c-3cba-4437-910c-5d956ca7ca41.png)
in step 2

![image](https://user-images.githubusercontent.com/15613121/147559129-60d29284-d77e-4e38-895e-38f759455da0.png)

2021-12-29 01:45 UTC, hyzx86 commented
Hi @Skrypt  ，Can you help review this PR?

2022-02-24 10:07 UTC, hyzx86 commented
Hi @Skrypt Is there anything wrong with this change?

2022-02-24 15:17 UTC, hishamco requested changes

2022-02-25 01:45 UTC, hyzx86 commented
@hishamco  Done.

2022-02-25 05:37 UTC, hishamco commented
Why the build failed?

2022-02-25 07:00 UTC, hishamco commented
I re-run the jobs, the build is pass

2022-02-25 07:02 UTC, hishamco approved these changes

2022-02-25 17:34 UTC, Skrypt approved these changes

2022-02-25 20:25 UTC, jtkech commented
Not sure I agree with this one, it fixes some scenarios but breaks other ones, e.g. after the execution of a `RetrieveContentTask` we may want (through the correlationId) to be in sync with the retrieved contentItemId even if an existing correlationId is already set. For other scenarios we have e.g. the `Set Output` and `Set Property` activities allowing to set and then retrieve a previous correlationId

For your scenario we have the oob `User Task` activity that halts the workflow until the user execute an action on a content item, in the activity settings you can define the action and the user role that can do the action, here the action could be named e.g. `Approve`, in that case if you edit the related content item you will see an `Approve` button that you will be able to click if you have the permission.

2022-02-26 04:25 UTC, hyzx86 commented
Hi @jtkech ，

> after the execution of a RetrieveContentTask we may want (through the correlationId) to be in sync with the retrieved contentItemId even if an existing correlationId is already set.

I think this operation is a little too subtle, and no one knows it without documentation and without looking at the code
As a workflow node, it should not affect the global properties of the entire workflow, it should only take the input and output the appropriate content, in this Issue I even feel that there is no need to check, we can get all the information through `LastResult`

In addition, the approval I refer to is not just approval through OC interface, if I want users to approve by email. Some dynamic scripts cannot be executed

2022-02-26 07:00 UTC, jtkech commented
@hyzx86 

Yes I understand your use case ;) But still not sure that the correlationId should always stay the same for the whole WF execution, particularly after the retrieve content task, maybe an activity option to not override an existing correlationId.

Maybe here your signal_url would need to be correlated with the global `WorkflowId`, not the `ContentItemId`, hmm can be done by inserting between step 1 and 2 a correlate task that just set the correlationId to null, in that case I think that the signal_url token will use the workflowId instead.

Anyway I don't want to block your PR, so I will let others triage it.

2022-02-26 21:16 UTC, jtkech commented
> I remember that in the signal task if the corrlationID is empty, it creates a new ID instead of using the workflow ID directly.

There is no signal task, only a signal event, and we can generate a signal url through a `SignalMethodProvider` or a `signal_url` liquid filter (as here), that targets the `HttpWorkflowController` that will trigger the related workflow, in both ways to generate the url if `CorrelationId` is null or empty the `WorkflowId` is used in the payload.

> The workflow ID may not exist because the signal task can also start the workflow

I don't think so, on each `NewWorkflow()` a new `WorkflowId` is generated.

Just tried to add just before step 2 a `CorrelateTask` with no value that I named "Decorrelate", yes when we edit the halted instance we still see the `CorrelationId` set to the 2nd contentItemId, but in the approval page the `signal_url` was already generated with the `WorkflowId`, then when I clicked on an Approve/Reject link the WF was resumed.

2024-01-28 23:17 UTC, Piedone commented
Is this something you'd like to revisit any time soon @hyzx86 or should we close?

2024-01-29 07:46 UTC, hyzx86 commented
> Is this something you'd like to revisit any time soon @hyzx86 or should we close?

Hi @Piedone  , Combined with the problems mentioned by JK, I don't think there will be any problems with my PR

The existing code will always update `CorrelationId`, I'm just adding a check

2024-01-29 20:55 UTC, Piedone commented
OK then! @hishamco @Skrypt you've reviewed this previously, please check this out if you still approve. Also, Hisham you added `dontmerge`, please check that's still applicable.

2024-01-30 15:17 UTC, Skrypt commented
It's non-breaking as you can always still update the correlationId by using different methods as mentioned by @hyzx86

2024-01-31 03:09 UTC, hyzx86 commented
@Skrypt ,  Maybe I can add a script function to this PR
Just like `setCorrelationId(string)`  ?

2024-01-31 14:06 UTC, Skrypt commented
Yeah, maybe instead of setting it from server side we could have a script that would affect it. That would be non-breaking.

2024-03-13 17:23 UTC, Piedone commented
Would you like to get back to this, @hyzx86?

2024-03-13 17:51 UTC, Piedone commented
What you have discussed last:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/fbe3dbe4-6b52-497d-8a11-aad25e69a835)

2024-03-14 02:15 UTC, hyzx86 commented
@Piedone ，Ok, I'll start a new PR

2024-03-14 04:17 UTC, hyzx86 commented on src/docs/releases/1.9.0.md
> +
Maybe a friend who is good at English can help me adjust this text.

2024-04-21 19:24 UTC, Piedone commented
@Skrypt can you please elaborate on why do you think this needs triage? What should we be mindful of during the triage?

2024-04-22 13:52 UTC, Skrypt commented
Waiting on @hyzx86 to know if he implemented what I suggested. If it is done then we need to review/test that code again to make sure it is fine.

2024-04-22 13:54 UTC, Piedone commented
Since this is a non-breaking change (right?) why wouldn't we merge if it otherwise looks good?

2024-04-22 14:37 UTC, Skrypt commented
Yeah, he seems to have added the method. I'd say, let's merge it.

2024-04-22 15:41 UTC, Piedone commented
OK, please approve, and you @hishamco (since you reviewed previously).

2024-04-22 15:52 UTC, Skrypt approved these changes

2024-04-22 19:54 UTC, hishamco commented on src/docs/releases/1.9.0.md
> +`CreateContentTask`, `RetrieveContentTask` and `UpdateContentTask`, in previous versions, the workflow's CorrelationId was updated each time with the ContentItemId of the current content item;
```suggestion
`CreateContentTask`, `RetrieveContentTask`, and `UpdateContentTask`, in previous versions, the workflow's CorrelationId was updated each time with the ContentItemId of the current content item;
```

2024-04-22 19:54 UTC, hishamco approved these changes

2024-04-22 20:20 UTC, merged