Add Navigation Abstractions APIs
OrchardCMS/OrchardCore pull request #11157
Opened 2022-02-10 16:41 UTC by hishamco

Move some of navigation types into navigation abstractions project

2022-02-11 07:53 UTC, hishamco commented on src/OrchardCore/OrchardCore.Navigation.Core/OrchardCore.Navigation.Core.csproj
> -    <ProjectReference Include="..\OrchardCore.Infrastructure.Abstractions\OrchardCore.Infrastructure.Abstractions.csproj" />
Exactly, I just fix it and move Pager related types into abstractions, the commit is ready in my local. I will push it soon

2022-02-11 16:06 UTC, deanmarcussen commented
How many files are actually left in the Core project after this?

2022-02-11 20:59 UTC, hishamco commented
The implementation types, which are 2 or 3 I think, this happen after we moved pager related types. If anyone disgree with move pager types I will move them back

2022-02-11 21:01 UTC, hishamco commented
I don't think it's a matter of no. of file. OC.Email.Core for instance has only one services, but the separation make them clear. So my doubt now about pager related types coz OC.List module are related to them

2024-03-13 17:35 UTC, Piedone requested changes
This would break like a third of the modules out there, since you'd need to add a new package reference to every module having a menu.

We shouldn't move around things just for the sake of it without much consideration. I've seen you do a lot of such stuff Hisham, and I'd discourage you from doing this: refactoring to remove clutter is good, but only if you involve the feedback of others (i.e. is it an issue that others agree with being an issue?), and it's non-breaking for our users or the refactoring is so much in-depth and useful that it makes it worthwhile. Moving around a few classes to do some polishing is not worth it. I can empathize with the sentiment, as I want things to be tidy too, but with a project like OC we need to consider the bigger picture.

2024-03-13 18:29 UTC, Piedone commented
Breaking changes are sometimes necessary, but we should only have them when they are indeed necessary and enable something important. Not for small clean-ups.

2024-03-13 18:30 UTC, Piedone commented
BTW I suggest you open issues instead of PRs for such things first, because then we can discuss it before you put time into doing them.

And this PR I suggest closing.

2024-03-13 18:33 UTC, closed without merging