Add descriptions to content-type Fix #11827
OrchardCMS/OrchardCore pull request #11842
Opened 2022-06-09 22:06 UTC by CrestApps

Add content description to the content-type just like we have for content-parts.

Accommodate #1182
![Screenshot_1](https://user-images.githubusercontent.com/24724371/172953184-06a3506a-400e-4f07-85c0-c177e815edfa.png)
7
![Screenshot_2](https://user-images.githubusercontent.com/24724371/172953189-977e3561-1920-449f-b858-2947364685f4.png)

2022-06-09 22:12 UTC, hishamco commented
I'm not sure if there's a need to display a technical name?!! But agree with adding a description when it's needed

2022-06-09 23:04 UTC, CrestApps commented
@hishamco I thought it would be helpful. In my case, I could just look at the technical name without having to even add description. During the call today @sebastienros mention to add it.

2022-06-09 23:51 UTC, hishamco requested changes

2022-06-09 23:51 UTC, hishamco commented on src/OrchardCore/OrchardCore.ContentManagement.Abstractions/Metadata/Settings/ContentTypeSettings.cs
> +        /// Gets or sets the description name of the type.
content type

2022-06-09 23:51 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/Shared/DisplayTemplates/EditTypeViewModel.cshtml
> +    <div class="row"><div class="col hint"> @settings.Description</div></div>
```html
@if (!string.IsNullOrEmpty(entry.Description))
{
    <div class="row">
        <div class="col">
            <p class="mb-0"><small class="text-muted">@settings.Description</small></p>
        </div>
    </div>
}
```

2022-06-10 00:10 UTC, CrestApps commented on src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/ContentTypeSettings.Edit.cshtml
> +    <span class="hint">@T["(Optional) Description of the type"]</span>
done

2022-06-10 06:45 UTC, hishamco approved these changes

2022-06-14 03:47 UTC, Skrypt approved these changes

2022-06-16 17:58 UTC, sebastienros approved these changes

2022-06-16 17:58 UTC, merged