Align the Getting Started documentation with .NET 6. Fix #11888
OrchardCMS/OrchardCore pull request #11892
Opened 2022-06-21 18:51 UTC by CrestApps

Fix #11888

2022-06-21 20:44 UTC, hishamco requested changes

2022-06-21 20:44 UTC, hishamco commented on src/docs/getting-started/README.md
> +Open `Project.cs` file. Remove the following line "if exists"
Project or Program?

2022-06-21 20:44 UTC, hishamco commented on src/docs/getting-started/README.md
> +
Extra line

2022-06-21 20:44 UTC, hishamco commented on src/docs/getting-started/README.md
> +Finally, remove the default `Pages` and/or `Views` folder to allow OrchardCore to render the views from the theme.
from the **current/selected** theme.

2022-06-21 20:54 UTC, CrestApps commented on src/docs/getting-started/README.md
> +Finally, remove the default `Pages` and/or `Views` folder to allow OrchardCore to render the views from the theme.
active theme?

2022-06-21 22:23 UTC, hishamco approved these changes

2022-06-30 04:12 UTC, CrestApps commented
> Might be worth updating the [project templates](https://github.com/OrchardCMS/OrchardCore/tree/main/src/Templates/OrchardCore.ProjectTemplates/content) as well to use the .NET 6 minimal hosting model.

Good idea. I suggest you create a new issue for that.

2022-06-30 16:22 UTC, hishamco commented
> Might be worth updating the [project templates](https://github.com/OrchardCMS/OrchardCore/tree/main/src/Templates/OrchardCore.ProjectTemplates/content) as well to use the .NET 6 minimal hosting model.

I think this tracked in another PR, so it's fine to merge this

2022-06-30 19:14 UTC, merged