Fix errors in code prompts
OrchardCMS/OrchardCore pull request #11973
Opened 2022-07-08 16:55 UTC by hyzx86

2022-07-08 17:33 UTC, hishamco requested changes

2022-07-08 17:33 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Workflows/Http/Scripting/HttpMethodsProvider.cs
> -                        return sr.ReadToEndAsync().GetAwaiter().GetResult(); ;
Nice catch

2022-07-08 17:33 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.AuditTrail/Views/AuditTrailEventTags.SummaryAdmin.cshtml
> +    </span>
Remove the extra whitespace

2022-07-09 06:52 UTC, hishamco approved these changes

2022-07-09 16:27 UTC, Skrypt approved these changes

2022-07-09 17:33 UTC, merged