Fix Cors policy changes may require a site reload to be activated
OrchardCMS/OrchardCore pull request #12062
Opened 2022-07-22 01:48 UTC by infofromca

Fix #9841

2022-07-22 04:01 UTC, jtkech approved these changes

2022-07-22 13:18 UTC, hishamco requested changes
LGTM after removeing the extra line

2022-07-22 13:18 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Cors/Controllers/AdminController.cs
> +
Remove extra new line

2022-07-22 15:46 UTC, hishamco approved these changes

2022-07-22 16:08 UTC, hishamco requested changes
Seems you miss to add a warning alter in the view like what usually did in other modules

https://github.com/OrchardCMS/OrchardCore/blob/c255456bf1d9093d13447e17485a23a1253f3e9b/src/OrchardCore.Modules/OrchardCore.Localization/Views/LocalizationSettings.Edit.cshtml#L5

2022-07-23 20:38 UTC, infofromca commented
just add a warning alter. by following OpenId module.
by the way, I found that there is also no  warning alter on the Recipe module

2022-07-23 21:03 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Cors/Views/Admin/Index.cshtml
> +            <button type="button" class="btn btn-primary" v-on:click="$emit('ok', policy, $event)">@T["Save and reload the tenant"]</button>
`Save` is fine, but where's the alert?

2022-07-23 21:04 UTC, hishamco commented
> by the way, I found that there is also no warning alter on the Recipe module

Let me verify and fix if there's something missing

2022-07-24 02:21 UTC, hishamco commented
The PR #12069 is created

2022-08-03 22:11 UTC, rserj commented
@sebastienros can we merge it? 
@jtkech I have multiple instances of Orchard Core running at the same time, will Tenant restart on all of the stacks?

2022-08-03 23:01 UTC, hishamco commented
@rserj I requested few changes that are not applied yet!!

2022-08-03 23:17 UTC, jtkech commented
@rserj 

Yes if you have a stateless config e.g. shell settings coming from database and enabled the Tenant.Distributed feature needing e.g a concrete implemenation of a distributed cache e.g. Redis cache and then recommended Redis lock.

2022-08-07 17:30 UTC, hishamco commented
@infofromca could apply the requested changes?

2022-08-11 20:42 UTC, hishamco approved these changes

2022-08-11 20:44 UTC, merged