Update the grouping logic for categories
OrchardCMS/OrchardCore pull request #12411
Opened 2022-09-13 22:55 UTC by MikeAlhayek

Fix #12410

2022-09-14 03:17 UTC, hishamco requested changes

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/ShortcodeModal.cshtml
> +    <script depends-on="shortcodes" at="Foot">
Extra space

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/ShortcodeModal.cshtml
> +    .Distinct(StringComparer.OrdinalIgnoreCase)
Intend lines 15-17

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Edit.cshtml
> +            {
Intend the initializer block

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Edit.cshtml
> +                                 placeholder="@T["Type to search"]"
Remove extra whitespace

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Edit.cshtml
> +    .Distinct(StringComparer.OrdinalIgnoreCase)
Intend lines 8-10

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +                                 placeholder="@T["Type to search"]"
Remove extra spaces

2022-09-14 03:17 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +    .Distinct(StringComparer.OrdinalIgnoreCase)
Intend lines 8-10

2022-09-14 14:43 UTC, MikeAlhayek commented
@hishamco I undid the changes that were auto done by Visual Studio.

2022-09-15 06:37 UTC, hishamco requested changes
Please fix the format everywhere

2022-09-15 06:37 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +@{
Extra space

2022-09-15 06:37 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +            </div>
Extra space

2022-09-15 06:37 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +            </div>
Extra space

2022-09-15 06:37 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +        document.getElementById('shortcodeCategories'),
Extra space

2022-09-15 06:37 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Edit.cshtml
> +    var jCategories = JsonConvert.SerializeObject(categories);
Extra space

2022-09-15 13:23 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Views/Admin/Create.cshtml
> +@{
I don't see these spaces in the diff.

2022-09-15 17:44 UTC, merged