change query schema editor to monaco-editor
OrchardCMS/OrchardCore pull request #12458
Opened 2022-09-20 15:01 UTC by hyzx86

Encountered a strange problem,
No adjustment can make the editor effective on this page
Can someone help to see what's going on?

Is it because monaco conflicts with codemirror?

![image](https://user-images.githubusercontent.com/15613121/191293492-cb946dab-23da-40ec-8ae1-1a6e04fc14cb.png)

2022-09-20 15:12 UTC, hyzx86 commented
However, the monaco editor still does not work after I have commented all the references to the codemirror..

2022-09-20 15:16 UTC, hyzx86 commented
@hishamco @Skrypt Can you help me look at this problem?

2022-09-20 15:31 UTC, Skrypt commented
> No adjustment can make the editor effective on this page

Can we see a screencast of the actual issue to define what it is?

2022-09-20 15:39 UTC, hyzx86 commented
https://user-images.githubusercontent.com/15613121/191302632-f79c9c22-3fd4-4abe-8810-0a232fd6801d.mp4

2022-09-20 15:42 UTC, hyzx86 commented
This is a clearer version
https://user-images.githubusercontent.com/15613121/191303275-9b922f85-d421-4a22-8c34-fc57b655daa0.mp4

2022-09-20 15:46 UTC, hyzx86 commented
🤣Done ， I have to change the editor container to div instead the textarea

![image](https://user-images.githubusercontent.com/15613121/191304347-aa085093-497e-4afc-a8f8-665995fd204f.png)

2022-09-21 05:18 UTC, hishamco requested changes
Please check the format in every PR, also share a screen cast as @Skrypt suggested

2022-09-21 05:18 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Queries/Views/Query.Fields.Edit.cshtml
> +
Remove extra line

2022-09-21 05:18 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Queries/Views/Query.Fields.Edit.cshtml
> +    <div id="@Html.IdFor(x=>x.Schema)_editor" style="min-height: 300px;" class="form-control"></div>
Html.IdFor(x => x.Schema)

2022-09-22 18:10 UTC, sebastienros approved these changes

2022-09-22 18:26 UTC, merged