Add documentation for YesSQL breaking change
OrchardCMS/OrchardCore pull request #12681
Opened 2022-10-21 17:32 UTC by Skrypt

Fixes #12653, Fixes #12679

2022-10-21 17:49 UTC, MikeAlhayek approved these changes

2022-10-21 17:57 UTC, Skrypt commented
Weird licence/cla limitation.

2022-10-21 18:00 UTC, hishamco requested changes

2022-10-21 18:13 UTC, Skrypt commented on src/docs/releases/1.5.0.md
> +If you do not want to not encrypt the communication at all, you can use `Encrypt=false`.
Fixed and also changed on the issue comment where I took that sentence from.

2022-10-21 18:15 UTC, Skrypt commented
Anyone else than me can merge this?

2022-10-21 18:33 UTC, hishamco approved these changes

2022-10-23 17:49 UTC, ns8482e commented
> Weird licence/cla limitation.

It seems something broken(may be auth) between dnf cla service and orchard cms org

2022-10-23 18:56 UTC, Skrypt commented
I just tested this here with Elsa and it works:
https://github.com/elsa-workflows/elsa-core/pull/3379

So, it is something broken with our CI or our Github config.

2022-10-23 19:21 UTC, jtkech commented
@Skrypt 

About the cla maybe related to github settings of the repo, would need to have access rights.

After reading some related issues, try to merge dev in your branch and push it to see if it unlocks this cla check, maybe it needs to be in sync with the last dev whose last commits are not marked as verified.

Not sure at all, just an idea ;)

2022-10-23 19:33 UTC, ns8482e commented
This status you get for previously successful pr  https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=12671

2022-10-23 19:40 UTC, jtkech commented
Oops

2022-10-23 19:43 UTC, Skrypt commented
hmm ok, this is not good. How can the license from DNF disappear like this?

2022-10-25 19:36 UTC, merged