Remove extra semicolons
OrchardCMS/OrchardCore pull request #12987
Opened 2022-12-24 03:27 UTC by hyzx86

2022-12-24 11:37 UTC, hishamco requested changes
Also we can form the condition as I suggested

2022-12-24 11:37 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Media/Fields/MediaFieldAttachedFileNameExtensions.cs
> +            return filenames != null ? filenames.ToObject<string[]>() : Array.Empty<string>();
```suggestion
            return filenames != null
                ? filenames.ToObject<string[]>()
                : Array.Empty<string>();
```

2022-12-24 11:38 UTC, hishamco approved these changes

2022-12-24 11:58 UTC, merged

2022-12-27 20:08 UTC, sebastienros commented
And others ...
https://grep.app/search?q=%3B%20%3B&filter[repo][0]=OrchardCMS/OrchardCore