Update localization README regarding pluralization
OrchardCMS/OrchardCore pull request #13141
Opened 2023-01-25 14:04 UTC by rjpowers10

Fixes #9917

A while back I raised an issue about the guidance around using the Plural method. I think we shouldn't be hardcoding a "1" into the singular form because the singular form can be used for counts other than 1. French, for example, uses the singular form for both 0 and 1.

It didn't seem like a consensus was reached and then the discussion went quiet, so I'm submitting this draft PR.

2023-01-25 14:04 UTC, rjpowers10 commented
cc @hishamco

2023-01-25 14:23 UTC, hishamco commented
Much better

2024-01-10 20:32 UTC, hishamco commented
@rjpowers10 can we make this "Ready for review" to take it seriously, it took a long time :)

2024-03-13 22:03 UTC, Piedone requested changes

2024-03-13 22:03 UTC, Piedone commented on src/docs/reference/modules/Localize/README.md
Reading through https://github.com/OrchardCMS/OrchardCore/issues/9917 I learned a lot :). But we need others to have a quick understanding of what's happening too, why does the singular example include a parameter? Could you please add a single paragraph of explanation under `## Pluralization` about the differences between languages like English and French, and why you as a developer would use a parameter even for the singular form?

2024-04-10 16:25 UTC, Piedone commented
Would you like to get back to this, @rjpowers10?

2024-04-15 22:18 UTC, Piedone approved these changes

2024-04-15 22:19 UTC, Piedone commented
Thank you! Next time when you're done addressing all feedback of a review, click ["Re-request review"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#re-requesting-a-review) in the top-right corner for each reviewer when you're ready for another round of review, so they know that you're done.

2024-04-15 22:19 UTC, merged