Add GetClientIpAddress() helper
OrchardCMS/OrchardCore pull request #13894
Opened 2023-06-21 20:07 UTC by MikeAlhayek

@jtkech

2023-06-21 21:48 UTC, jtkech commented
Looks good but `IOrchardHelper` is most commonly used to provide Razor extensions, particularly for decoupled cms, never seen injected elsewhere, so maybe better to provide an `HttpContext` extension.

2023-06-21 22:14 UTC, MikeAlhayek commented
@jtkech I understand. `IOrchardHelper` is injected when `AddOrchardCore()` extension is built. So it is a service that would always be available by default. I chose `IOrchardHelper` because one time I have a convo with @sebastienros and he suggested against adding extension for `HttpContext` directly. Since this is an extension of OC it maybe best if extend OC classes instead of .NET.

2023-06-21 22:41 UTC, jtkech commented
Okay but not sure when more related to a given class and to not have too many undifferentiated `IOrchardHelper` extensions, personally I prefer `httpContext.GetClientIpAddress()` than `orchardHelper.GetClientIpAddress()`, but no problem if @sebastienros prefers.

2023-06-21 22:48 UTC, MikeAlhayek commented
I personally also find it more appealing `httpContext.GetClientIpAddress()` over `orchardHelper.GetClientIpAddress()`. @sebastienros can you chime in here to know which route is best for OC?

2023-06-22 10:36 UTC, hishamco requested changes

2023-06-22 10:36 UTC, hishamco commented on src/OrchardCore/OrchardCore.Abstractions/Extensions/OrchardHelperExtensions.cs
> +    public static IPAddress GetClientIpAddress(this IOrchardHelper orchardHelper)
I agree with the others this could be an extension for `HttpContext` not `IOrchardHelper`

2023-07-11 20:12 UTC, MikeAlhayek commented
I created an interface `IClientIpAddressAccessor` as per @sebastienros recommendation.

2023-07-12 23:32 UTC, merged