Azure ID -> Microsoft Entra ID
OrchardCMS/OrchardCore pull request #14004
Opened 2023-07-16 04:43 UTC by hishamco

Addresses #13990

2023-07-17 16:30 UTC, Piedone requested changes
Please don't resolve my comments when you're done with something so I can track feedback (except for code suggestions that get resolve automatically). However, you can keep track whether you've addressed something with a reaction under the message for example if you want to.

2023-07-17 16:30 UTC, Piedone commented on mkdocs.yml
> +      - Microsoft Entra ID / Azure AD integration: docs/guides/microsoft-entra-id-integration/README.md
```suggestion
      - Microsoft Entra ID (Azure AD) integration: docs/guides/microsoft-entra-id-integration/README.md
```

2023-07-17 16:30 UTC, Piedone commented on src/docs/guides/microsoft-entra-id-integration/README.md
> +# Use Microsoft Entra ID / Azure AD as an external identity provider
Run the docs locally, see https://docs.orchardcore.net/en/latest/docs/topics/docs-contributions/, to see if anything got broken. There's this one at least:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/7c85485d-df92-471c-8e1c-be2fc0d8762f)

2023-07-17 17:29 UTC, MikeAlhayek approved these changes

2023-07-17 21:07 UTC, merged

2023-07-17 22:25 UTC, Piedone commented
Why did you merge this, @agriffard? I didn't approve it, and there are pending comments of mine that Hisham couldn't address.

2023-07-18 03:44 UTC, hishamco commented
Thanks, @MikeAlhayek for the updates that you did

> Why did you merge this, @agriffard? I didn't approve it, and there are pending comments of mine that Hisham couldn't address.

Seems he merge when Mike approved :) anyhow I will check your comments Zoltan

2023-07-18 07:48 UTC, agriffard commented
> Why did you merge this, @agriffard? I didn't approve it, and there are pending comments of mine that Hisham couldn't address.

Sorry @Piedone , I saw that @MikeAlhayek had made some changes related to your comments and approved the PR so I thought it was ready to merge.

2023-07-18 18:08 UTC, Piedone commented
I see, no problem.