Remove extra warning alert from SmtpSettings.Edit
OrchardCMS/OrchardCore pull request #14299
Opened 2023-09-09 19:10 UTC by hishamco

Fixes #14286

2023-09-09 19:13 UTC, hishamco commented
I noticed this happened after the changes in https://github.com/OrchardCMS/OrchardCore/pull/14150 , so there are some other places that we need to fix

Before that, I'd like to ask @MikeAlhayek if he has an idea to override the alert - if it's required - when he did this change before

2023-09-09 19:31 UTC, agriffard commented
Is there the same on /admin/settings/localisation? Can you please fix it too?

2023-09-10 11:58 UTC, hishamco commented
Yes, there are already in my local, but I need @MikeAlhayek feedback coz some need tweaks

2023-09-10 12:00 UTC, hishamco commented
The once that need to override are related to AUTH modules

2023-09-10 16:54 UTC, MikeAlhayek commented
@hishamco I think the problem is happening because the `Settings_Wrapper__General` wrapper is injected every time. You should undo all your changes and try adding the following code before https://github.com/OrchardCMS/OrchardCore/blob/033e0ae1f5e1ed421b5e919082be2fe40d4f2c53/src/OrchardCore.Modules/OrchardCore.Settings/Drivers/DefaultSiteSettingsDisplayDriver.cs#L33

```
if (!context.GroupId.Equals(GroupId, StringComparison.OrdinalIgnoreCase))
{
    return Task.FromResult<IDisplayResult>(null);
}
```

To clean up `DefaultSiteSettingsDisplayDriver` a bit more, I would even add a new method like this
```
private bool IsGeneralSettings() => context.GroupId.Equals(GroupId, StringComparison.OrdinalIgnoreCase)
```
Then use `IsGeneralSettings()` on line 33 and in line 52. 

On line 52, I would even save indentation by replacing like 52 with this
```
if (!IsGeneralSettings())
{
    return null;
}
```

2023-09-11 22:19 UTC, jtkech commented
Maybe to make it simpler, see https://github.com/OrchardCMS/OrchardCore/issues/14286#issuecomment-1714659693

2023-09-12 15:56 UTC, MikeAlhayek requested changes

2023-09-12 15:56 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Settings/Drivers/DefaultSiteSettingsDisplayDriver.cs
> +            if (IsGeneralSettings(context))
Can you please save dentition here by adding a return when not group? Look what I did in my PR.

2023-09-12 15:56 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Settings/Drivers/DefaultSiteSettingsDisplayDriver.cs
> +        private static bool IsGeneralSettings(BuildEditorContext context)
@hishamco 
Maybe rename this to `IsGeneralGroup`. Ping me once done and I'll merge it

2023-09-12 16:18 UTC, MikeAlhayek approved these changes

2023-09-12 16:26 UTC, merged