New content transfer module
OrchardCMS/OrchardCore pull request #14630
Opened 2023-11-04 00:28 UTC by MikeAlhayek

This feature will enable the user to import and export content items from and into OC

**Important** this PR is not yet ready to be reviews. Let's hold off any code review until it is ready to prevent time wasting.
To do
- [ ] Create UI to show list of `ContentTransferEntry` instances along with the status.
- [ ] Create a background processor to process `ContentTransferEntry` instances by committing 200 rows at a time. The idea if the tenant was restarted, we would lose no more than 200 already processed records.
- [ ] Add option for the import process so the user can add behavior (Should we validate content items? if something fails validation, should be ignore or store it any way?
- [ ] Document the module so users know how to use it
- [ ] Clean up the code

2023-11-06 20:14 UTC, hishamco commented
What about the deployment module?

2023-11-06 20:41 UTC, MikeAlhayek commented
> What about the deployment module?

The deployment module import/export recipe. This module import/exports content items using csv or excel files. I think having it's own module is better.

2023-11-06 22:03 UTC, MichaelPetrinolis commented
Hi @MikeAlhayek, I agree with having a flat file import/export module, but I would like to reuse the recipes for the importing/exporting of the data. The import/export flat files module should define multiple mappings between file and contenttype, and when importing it should convert records to multiple recipe.json files for Content. A background job should execute the created recipe files and mark the job as done, when all batches are handled.

The same logic could be for the export, an asynchronous background job to get the recipe.json data, convert the records to a flat file in batches, and when all the batches are complete, the job should be marked as completed with a file available for download.

Another thing is the licensing of EPPlus, it is not MIT, it was LGPL until v4 and from v5 and up it is under Polyform Noncommercial 1.0.0 license. see https://www.epplussoftware.com/en/LicenseOverview

PS
I have not read the code to see how you implement the module, I suppose that you reimplement the import/export from the database to/from the files

2023-11-06 22:04 UTC, MichaelPetrinolis commented
Hi @MikeAlhayek, I agree with having a flat file import/export module, but I would prefer to reuse the recipes for the importing/exporting of the data. The import/export flat files module should define multiple mappings between file and contenttype, and when importing it should convert records to multiple recipe.json files for Content. A background job should execute the created recipe files and mark the job as done, when all batches are handled.

The same logic could be for the export, an asynchronous background job to get the recipe.json data, convert the records to a flat file in batches, and when all the batches are complete, the job should be marked as completed with a file available for download.

Another thing is the licensing of EPPlus, it is not MIT, it was LGPL until v4 and from v5 and up it is under Polyform Noncommercial 1.0.0 license. see https://www.epplussoftware.com/en/LicenseOverview

PS
I have not read the code to see how you implement the module, I suppose that you reimplement the import/export from the database to/from the files

2023-11-06 23:02 UTC, MikeAlhayek commented
@MichaelPetrinolis Yes, the EPPlus license is a problem. Maybe, we'll use a different library (not worried about it for now). Once everything is ready, it should be an easy task to switch library assuming there are free libraries out there that would convert 

Why do you suggest using recipes to import? The idea is to queue up files, a background process will process the records in batches after a validation is done. With this approach, we can monitor the process (like how many failed, successes and total processes). We could even download the failed records.

The problem with creating recipe files and try to import them, we can't tell which records failed and there no good way to provide feedback on the process. And if I am able to create the content item, at that point I don't know if there is benefit of writing that object to a recipe over writing it to the database directly. Sterilizing and deserializing objects will over an overhead. But if you think there are benefits, I would like to hear you out more

2023-11-07 15:24 UTC, MikeAlhayek commented
@MichaelPetrinolis yes I already use the content manager in my code. I still don't think we need the recipes here. Once I finish, I'll ping you so you can test drive it and provide your feedback. We can always change how we handle the last step (saving) the records later on to a better way if we agree that indeed there is a better way.

2023-12-01 16:33 UTC, MikeAlhayek commented
@cocoke I update the readme file in this PR with info on how to define field, part, or content importer. The description above shows the remaining items. One thing I have not yet attempted is attempt to import a file and let the background task process it and ensure everything is working as expected. 

Let me know which item you want to tackle so we are not stepping on each other toes. But, I think you should be able to first this branch and submit a PR into this branch not main.

2024-01-29 14:56 UTC, hyzx86 commented
Hi @MikeAlhayek ， Notice today that this PR has been merged into Dev. Maybe we can use ClosedXML instead of EPPlus
https://github.com/ClosedXML/ClosedXML/pull/2248

2024-01-29 16:14 UTC, MikeAlhayek commented
@hyzx86 yes that is the plan. If you like, feel free to help completing this PR. I have not had much time to finish it off.

2024-03-24 21:11 UTC, Piedone commented
Is this something you'd like to revisit any time soon @MikeAlhayek or should we close?

If you'd like to continue, could you please explain the following?

1. Why not extend the Deployment module to support multiple formats instead?
2. Why do we need multiple formats, to begin with?


Ad 2: Excel and CSV are quite specific to a given use-case. We at Lombiq built quite a few such export/import features over the years, but none of them were generic content item export/imports, and all of them were only single-direction to/from a non-OC app (and never between two OC apps).

They were all specific to that app. E.g., upload a CSV from an external system (that knows nothing about OC and content items), and generate content items from it or other save data to the DB (some values came directly from the CSV, some were calculated based on something else, some were transforms of the CSV data). Or export to Excel in a way that some other system will understand, which was unique to that system. Or even export specific items to PDF, using a PDF template.

I think that we can only provide a generic solution, but that will never be appropriate, people will need to customize it, and customize it in wildly different ways. Perhaps there is some lowest common denominator that's feasible to support, like some batch-processing feature that can handle arbitrary large uploaded import files and their processing with providers that make no assumptions (not even whether you export from or import into content items). And the first usage example would be the Deployment module. However, this is rather abstract.

2024-03-24 21:35 UTC, MikeAlhayek commented
Yes at some point I would like to finish it. Many people showed interest into it. The idea is to be able to import/import data from/to Excel or cvs format. In many cases people want to be able to export data in Excel format for other systems, client data export or any other reasons. Similarly, people may want to import external data into OC. This module will allow to do such a thing. This module is only for text data.


Deployment module allows you to build  deployment plan made of steps and is not text only. One can add media as deployment step. So it is a completely different concept. Not sure if you have a an idea where we can use the deployment module for this too.

2024-03-24 21:43 UTC, Piedone commented
While with some formats you wouldn't be able to export Media, I think everything else that Deployment Plans provide would be necessary here too (like filtering what to export, unless you only want to allow a single content item or all of them).

2024-03-24 21:46 UTC, MikeAlhayek commented
In this module, you export one content type at a time. The content type defines the file headers.

2024-03-24 22:19 UTC, Piedone commented
I see.

2024-03-25 04:36 UTC, hyzx86 commented
Recently I've been learning Odoo, which has a data initialization/import mechanism, maybe we can refer to it,
It uses CSV/XML to import data,
I was wondering if I could use this module as well, since Json format can sometimes seem unintuitive
Perhaps it's as simple as adding a deployment node of type contentData and referencing it to a specific file, like the template file currently does

https://github.com/odoo/odoo/blob/e8697f609372cd61b045c4ee2c7f0fcfb496f58a/odoo/addons/base/__manifest__.py#L29
https://github.com/odoo/odoo/blob/e8697f609372cd61b045c4ee2c7f0fcfb496f58a/odoo/addons/base/data/res.country.state.csv

2024-05-16 23:20 UTC, Piedone commented
Fixes https://github.com/OrchardCMS/OrchardCore/issues/7865?

2024-05-17 01:12 UTC, MikeAlhayek commented
Yes it should. Got to find time to complete this draft.

2024-05-19 04:40 UTC, hyzx86 commented
> Hi @MikeAlhayek , Notice today that this PR has been merged into Dev. Maybe we can use ClosedXML instead of EPPlus (https://github.com/ClosedXML/ ClosedXML/pull/2248)

As of today. `ClosedXML` has not yet released a new official version. 
Do we have any other options?

2024-05-19 04:52 UTC, MikeAlhayek commented
@hyzx86 maybe https://www.nuget.org/packages/DocumentFormat.OpenXml.  Are you planning to help finishing up this PR?

2024-05-19 04:58 UTC, hyzx86 commented
> @hyzx86 maybe https://www.nuget.org/packages/DocumentFormat.OpenXml. Are you planning to help finishing up this PR? 

Oh. That might be another question about this https://github.com/OrchardCMS/OrchardCore/issues/14941  🤣

2024-05-19 05:23 UTC, MikeAlhayek commented
No strong opinion here. If there is a draw back from using 3, we can use 2.

2024-09-13 20:11 UTC, MikeAlhayek commented
@brunoAltinet

2024-09-13 20:17 UTC, hishamco commented
@MikeAlhayek can you contribute this to OCC if you have time, otherwise I will move it there if you don't mind

2024-09-13 20:26 UTC, Piedone commented
This could also be resumed here.

2024-09-13 20:37 UTC, hishamco commented
I thought it's closed for a reason

2024-09-14 02:59 UTC, MikeAlhayek commented
The PR was closed because there was no activity on it for a while. I got too busy to complete it. It is 80% complete and needs more work. We agreed to put this in the framework so it's good where it is.

@brunoAltinet mentioned he may finish it! If not, hopefully I can find time to complete it.

2024-09-14 11:57 UTC, hishamco commented
Please fix the build & conflict

2024-11-14 00:25 UTC, MikeAlhayek commented
@brunoAltinet i am guessing you forgot about this one? Are you still going to be able to finish it off?

2026-03-23 23:16 UTC, MikeAlhayek commented
@MichaelPetrinolis @brunoAltinet @hyzx86 @Piedone better late than never? I finally had time to work on this PR and it is now ready. If you are are interested in Import/Export content item from Excel files, please test drive this PR. Hoping we can mere it soon.

2026-03-24 22:39 UTC, Piedone commented
Awesome! Two things before I'd check it:

- Could you please submit the `using` clean-up separately? Because that adds a lot of noise and a huge number of changes to comb through if one wants to be diligent.
- Would you please demo it on the next meeting?

2026-03-25 11:26 UTC, MikeAlhayek commented
@Piedone this was demoed yesterday. Please watch the recording. 

I’ll fix the usings via another branch.

2026-03-25 21:34 UTC, MikeAlhayek commented
@Piedone no more using changes in this PR. Feel free to watch the demo from 3/24/2026 and then checkout the code.

2026-03-28 01:01 UTC, Piedone commented
Thank you! I'll try to review this over the weekend.

For reference, demo is here: https://youtu.be/mugneTGE3AA?si=jtArEAbdigRXXEQT&t=2383.

2026-04-02 22:07 UTC, MikeAlhayek commented
@copilot+gpt-5.4 please fix the build errors by addressing all these warnings. We should be using `.TryGet<>` or `.GetOrCreate<>` instead of using `.As<>`

2026-04-02 22:38 UTC, MikeAlhayek commented
@copilot+gpt-5.4 there are still build errors due to warning. Don't stop fixing these errors until all everything is built successfully and tests are passing.

2026-04-08 00:11 UTC, Piedone requested changes

2026-04-08 00:11 UTC, Piedone commented on src/docs/reference/modules/ContentTransfer/README.md
Can you share the file you imported in the demo? I'd test with that. Even if privately.

2026-04-08 00:11 UTC, Piedone commented on src/docs/reference/modules/ContentTransfer/README.md
How about an option to select a Query to export based on? It's the ultimate customization, and with that, you can select the items based on any arbitrary logic.

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Views/Admin/Export.cshtml
> +                                <label class="form-check-label" for="exportPartial">@T["Partial Export"]</label>
"Filtered Export"?

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore/OrchardCore.ContentTransfer.Core/Models/ContentImportOptions.cs
> +    public const int AbsoluteMaxAllowedFileSizeInBytes = 100 * 1024 * 1024;
Why is that? Requests can be chunked, see the Media module with larger uploads.

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore/OrchardCore.ContentTransfer.Core/Handlers/AliasPartContentImportHandler.cs
There's a large amount of duplicated, or pattern-following code among these part handlers. Check if the amount of code can be reduced.

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore/OrchardCore.ContentTransfer.Core/Handlers/Fields/BooleanFieldImportHandler.cs
I'd consider CSV files as the lowest common denominator, since CSV import/export is commonly available in a system even if XLSX isn't. As another tabular format, I don't think it's conceptually different for data transfer. But have you considered if anything in this feature implicitly couples the logic to XLSX?

2026-04-08 00:11 UTC, Piedone commented on src/docs/reference/modules/ContentTransfer/README.md
> +- **Import**: The uploaded file is read in streaming batches. Only the current batch of rows is held in memory at a time. Processed rows are cleared before the next batch is loaded.
Do you mean these `Clear()`s? https://github.com/OrchardCMS/OrchardCore/blob/64299e07a4f74d11735cd842f70621897983724e/src/OrchardCore.Modules/OrchardCore.ContentTransfer/BackgroundTasks/ImportFilesBackgroundTask.cs#L351-L354 I'd consider these more part of the logic, not a memory optimization. For everything else, we have the GC.

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Controllers/AdminController.cs
The feature could benefit from some functional tests, like to at least test the basics of an export and an import.

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Controllers/AdminController.cs
> +                await _session.SaveChangesAsync();
Are these explicit transaction commits really necessary?

2026-04-08 00:11 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Migrations/ContentTransferMigrations.cs
> +    public async Task<int> UpdateFrom1Async()
This is a new feature, an update method shouldn't be necessary.

2026-05-16 16:57 UTC, MikeAlhayek commented on src/docs/reference/modules/ContentTransfer/README.md
Yeah that would be good too. We also talked about Data Orchestrator module instead of this one #19062. that one allows you to build a pipeline to define where the data is coming from and how to export it. It's more complex UI but more flexible that this one. If we go with this PR, we would add Query based export as follow up. don't want to expand this PR more that the current scope.

2026-05-16 17:23 UTC, MikeAlhayek commented on src/docs/reference/modules/ContentTransfer/README.md
[Article_Export.xlsx](https://github.com/user-attachments/files/27858170/Article_Export.xlsx)

2026-05-16 17:24 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Views/Admin/Export.cshtml
> +                                <label class="form-check-label" for="exportPartial">@T["Partial Export"]</label>
done

2026-05-16 17:24 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Controllers/AdminController.cs
> +                await _session.SaveChangesAsync();
removed

2026-05-16 17:25 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Migrations/ContentTransferMigrations.cs
> +    public async Task<int> UpdateFrom1Async()
removed

2026-05-16 17:28 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.ContentTransfer.Core/Handlers/AliasPartContentImportHandler.cs
It's intentional for maintainability (each handler is self-contained).

2026-05-16 17:34 UTC, MikeAlhayek commented on src/docs/reference/modules/ContentTransfer/README.md
> +- **Import**: The uploaded file is read in streaming batches. Only the current batch of rows is held in memory at a time. Processed rows are cleared before the next batch is loaded.
No. that means that when we process the records we process them in chunks and after processing a small chunk we commit them and not keep them in the database. We don't hold large amount of data in the memory. We call `SaveChangesAsync()` and remove all lists or data from the memory.

2026-05-16 18:03 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.ContentTransfer.Core/Models/ContentImportOptions.cs
> +    public const int AbsoluteMaxAllowedFileSizeInBytes = 100 * 1024 * 1024;
Now we supoprt chunking like the media

2026-05-16 18:03 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.ContentTransfer.Core/Handlers/Fields/BooleanFieldImportHandler.cs
CSV is also supported now.

2026-05-16 18:04 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentTransfer/Controllers/AdminController.cs
added some tests

2026-05-16 20:40 UTC, MikeAlhayek commented
@sebastienros I need a decision on this content transfer module, which is essentially merge-ready.

We also discussed the broader `Data Orchestrator` feature that would support import/export through pipelines (PR #19062), but that work is still incomplete and may never be finished due to time constraints.

We need to decide ASAP whether we:

* move forward with this PR and provide users with a practical import/export solution using `.csv` and `.xlsx`, or
* close it and rely on the possibility that we eventually come back to #19062.

Either way, we need clarity so I can determine how to implement this functionality in my own project as well (which is needed ASAP).

2026-05-20 15:35 UTC, MikeAlhayek commented
@Piedone if you have time, please review this requested changes. I like to wrap this one up ASAP. Thank you

2026-05-20 17:10 UTC, Piedone commented
I'll be able to get to this over the weekend.

2026-05-22 07:35 UTC, gvkries commented
@Piedone Before you bother to review this PR: the consensus from the triage meeting is to work on #19062 instead.

2026-05-22 10:37 UTC, Piedone commented
Ah OK, thank you!

2026-05-22 10:37 UTC, closed without merging