Adding the Issue Metrics Action to generate metrics on how we manage issues (Lombiq Technologies: OCORE-139)
OrchardCMS/OrchardCore pull request #15041
Opened 2024-01-10 23:17 UTC by Piedone

Fixes https://github.com/OrchardCMS/OrchardCore/issues/14585

2024-01-10 23:42 UTC, Piedone commented on .github/workflows/issue-metrics.yml
> +    branches: [ main, release/** ]
This is only for testing, needs to be removed before merge.

2024-01-10 23:45 UTC, Piedone commented
This needs to be fixed before we can adopt it: https://github.com/github/issue-metrics/issues/188. Or we can just accept that the "Time to answer" metric is broken for now, though I think that's quite crucial.

Here's are example issues:

- https://github.com/OrchardCMS/OrchardCore/issues/15051
- https://github.com/OrchardCMS/OrchardCore/issues/15052

2024-01-11 00:01 UTC, Piedone commented
Misunderstood it, we have no bug: https://github.com/github/issue-metrics/issues/188#issuecomment-1885936756.

2024-01-24 18:49 UTC, Piedone commented
@agriffard can you review this? It would be great to have it merged still in January, because then we'll see if it works as the scheduled workflow on the 1st February.

2024-01-25 23:43 UTC, hishamco requested changes

2024-01-25 23:43 UTC, hishamco commented on .github/workflows/issue-metrics.yml
> +    - name: Concatentate Issue and Pull Request Metrics
```suggestion
    - name: Concatenate Issue and Pull Request Metrics
```

2024-01-25 23:43 UTC, hishamco commented on .github/workflows/issue-metrics.yml
> +    - name: Concatentate Issue/PR and Discussion Metrics
```suggestion
    - name: Concatenate Issue/PR and Discussion Metrics
```

2024-01-27 08:33 UTC, hishamco approved these changes

2024-01-30 17:44 UTC, Piedone commented
Thanks!

2024-01-30 17:44 UTC, merged