Add onload attribute to ReCaptchaTagHelper
OrchardCMS/OrchardCore pull request #15283
Opened 2024-02-08 22:34 UTC by mroskamp

Add onload attribute to ReCaptchaTagHelper to allow specifying the onload callback to the reCAPTCHA script. fixes #15281

2024-02-08 22:38 UTC, hishamco commented
Why you remove the `ILocalizationService`? the build is fail

2024-02-08 22:43 UTC, mroskamp commented
> Why you remove the `ILocalizationService`? the build is fail

It was accidental. A fix is incoming.

2024-02-08 22:49 UTC, hishamco requested changes

2024-02-08 22:49 UTC, hishamco commented on src/OrchardCore/OrchardCore.ReCaptcha.Core/TagHelpers/ReCaptchaTagHelper.cs
> +            if (!string.IsNullOrWhiteSpace(OnLoad))
```suggestion

            if (!string.IsNullOrWhiteSpace(OnLoad))
```

2024-02-08 22:49 UTC, hishamco commented on src/OrchardCore/OrchardCore.ReCaptcha.Core/TagHelpers/ReCaptchaTagHelper.cs
> +            return settingsUrl.ToString();
```suggestion

            return settingsUrl.ToString();
```

2024-02-08 22:49 UTC, hishamco commented on src/OrchardCore/OrchardCore.ReCaptcha.Core/TagHelpers/ReCaptchaTagHelper.cs
> +            _resourceManager.RegisterFootScript(builder);
```suggestion

            _resourceManager.RegisterFootScript(builder);
```

2024-02-08 22:49 UTC, hishamco commented on src/OrchardCore/OrchardCore.ReCaptcha.Core/TagHelpers/ReCaptchaTagHelper.cs
> +            _localizationService = localizationService;
Revert the changes here

2024-02-09 15:27 UTC, hishamco approved these changes

2024-02-15 18:18 UTC, sebastienros approved these changes

2024-02-15 18:19 UTC, merged