Remove TitlePart wrapper when it is hidden
OrchardCMS/OrchardCore pull request #15471
Opened 2024-03-07 17:16 UTC by douwinga

Fixes #15382

2024-03-07 19:18 UTC, MikeAlhayek requested changes

2024-03-07 19:18 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Title/Views/ContentPart-TitlePart.Edit.cshtml
> +}
Add new line

2024-03-07 19:20 UTC, sebastienros commented
@douwinga PR is fine, did you actually face an issue with this empty wrapper? Or did you find the ticket and wanted to help fix it.

2024-03-07 19:20 UTC, sebastienros approved these changes

2024-03-07 21:57 UTC, merged

2024-03-07 22:35 UTC, douwinga commented
@sebastienros Just trying to contribute to become a better developer. Was looking for a ticket I could finish on my lunch break. This was the first one I found.

2024-03-07 22:42 UTC, sebastienros commented
So we are hoping this doesn't break anything, the issue wasn't to fix an actual problem but something that looked odd. It's totally possible that some other feature was using (or could use in the future) these wrappers even if the shape was not rendered (e.g. content preview, placement, shape debugger, ...)

2024-03-07 22:49 UTC, douwinga commented
Hmmm, I bet this change would actually cause an issue with admin templates and shape rendering. It would no longer obey the hide check. Should probably keep that check on the TitlePart.Edit. it seemed like an innocent change

2024-03-07 22:56 UTC, sebastienros commented
If you can do some test and see if nothing is broken, otherwise we'll just revert the change.

2024-03-07 23:14 UTC, sebastienros commented
> I wonder if these wrappers were just to give JavaScript something to target or something.

Definitely. Question is do these wrappers still like to have the div even if the part is not displayed ... I would say that if the wrapper doesn't bother, we should just keep it.

2024-03-08 00:01 UTC, MikeAlhayek commented
I tested the change before merging and it worked as expected with no issues. But another set of eyes wont hurt.

2024-03-08 02:28 UTC, douwinga commented
I was wrong. Having `{{ Model.Parts.TitlePart | shape_render }}` in an admin template does still obey the hidden setting. So far nothing else has broken either.

2024-03-08 03:00 UTC, douwinga commented
It breaks with a placement.json with the following:

```
{
  "TitlePart_Edit": [
    {
      "place": "Parts:0",
      "displayType": "Edit"
    }
  ]
}
```
If we do the `TitlePartOptions.GeneratedHidden` check in `TitlePart.Edit.cshtml` it works correctly as the only thing that is broken is that it no longer is checking that.

I can do a PR to just have it check in `TitlePart.Edit.cshtml` too and not just `ContentPart-TitlePart.Edit` if we think we are not just going to revert this change.

2024-03-08 03:02 UTC, douwinga commented
> shape debugger

Not sure what that is to test