Update Blazor CMS guide with multitenancy support and interactivity demo
OrchardCMS/OrchardCore pull request #15573
Opened 2024-03-24 22:34 UTC by psijkof

Extended the Blazor App Sample on OrchardCore.Samples, via PR: https://github.com/OrchardCMS/OrchardCore.Samples/pull/45

And extended the documentation that is waiting in this PR, here: https://github.com/OrchardCMS/OrchardCore/pull/15213

2024-03-25 00:55 UTC, hishamco commented on src/docs/guides/create-blazor-cms/README.md
> +         protected override async Task OnInitializedAsync()
Fix the formatting so the tab should be 4 spaces

2024-03-26 01:10 UTC, Piedone commented
Awesome! @ns8482e would you be interested to review?

2024-03-27 13:12 UTC, hishamco requested changes

2024-03-27 13:12 UTC, hishamco commented on src/docs/guides/create-blazor-cms/README.md
> +In this article, you will learn how to use Orchard CMS as a decoupled CMS with .NET Blazor (SSR/Server Interactive) Application.
```suggestion
In this article, you will learn how to use Orchard CMS as a decoupled CMS with the .NET Blazor (SSR/Server Interactive) Application.
```

2024-03-27 13:12 UTC, hishamco commented on src/docs/guides/create-blazor-cms/README.md
> +> You can add `.razor` files in the main Orchard Core Web application, however adding `.razor` files in Orchard Core modules are not supported. For this reason, and to have maximum reusability of you
```suggestion
> You can add `.razor` files in the main Orchard Core Web application, however adding `.razor` files in Orchard Core modules is not supported. For this reason, and to have maximum reusability of your razor components, always use the razor class library and add it as a reference to your Orchard Core Web project or Orchard Core module.
```

2024-04-03 00:17 UTC, ns8482e approved these changes

2024-04-03 11:57 UTC, agriffard commented
Add the path to the .md file in mkdocs.yml, below the 'How to guides' node to make it appear in the menu and in order to build the page.

2024-04-03 12:28 UTC, merged