Adjust content type condition to evaluate to true when no content is displayed and the operation for the given condition is a negation to address. Fixes #15452.
OrchardCMS/OrchardCore pull request #15603
Opened 2024-03-27 16:46 UTC by rwawr

Adjust content type condition to evaluate to true when no content is displayed and the operation for the given condition is a negation to address. Fixes #15452.

2024-03-27 18:16 UTC, Piedone commented
This is a follow-up from https://github.com/OrchardCMS/OrchardCore/pull/15602. And now there's no policy bot... Anyway, you accepted the CLA.

2024-03-27 18:19 UTC, Piedone approved these changes
This seems quite clear-cut to me, but I'm not sure if I'm missing something obvious. @deanmarcussen could you please also take a quick look?

2024-03-28 16:57 UTC, MikeAlhayek requested changes

2024-03-28 16:57 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Rules/Drivers/ContentTypeConditionEvaluatorDriver.cs
> +            if (!_contentTypes.Any())
```suggestion
            if (_contentTypes.Count == 0)
```

2024-03-28 17:05 UTC, rwawr commented on src/OrchardCore.Modules/OrchardCore.Rules/Drivers/ContentTypeConditionEvaluatorDriver.cs
> +using System.Linq;
```suggestion
```

2024-03-28 20:19 UTC, merged