fix #15737
OrchardCMS/OrchardCore pull request #15744
Opened 2024-04-12 15:30 UTC by infofromca

2024-04-12 19:49 UTC, hishamco requested changes

2024-04-12 19:49 UTC, hishamco commented on src/README.md
> +- **Database Support**. SQL Server, MySQL, MariaDB, PostgreSQL and SQLite. For MariaDB, select MySQL as the type of database and follow all the rules of MySQL.
```suggestion
- **Database Support**. SQL Server, MySQL, MariaDB, PostgreSQL, and SQLite. For MariaDB, select MySQL as the database type and follow all MySQL rules.
```

2024-04-12 19:49 UTC, hishamco commented on src/README.md
> +- **Document database abstraction**. Orchard Core CMS still requires a relational database, and is compatible with SQL Server, MySQL, PostgreSQL and SQLite, but it’s now using a document abstraction
```suggestion
- **Document database abstraction**. Orchard Core CMS still requires a relational database and is compatible with SQL Server, MySQL, PostgreSQL, and SQLite, but it’s now using a document abstraction (YesSql) that provides a document database API to store and query documents. This is a much better approach for CMS systems and helps performance significantly.
```

2024-04-12 20:29 UTC, hishamco approved these changes

2024-04-12 20:29 UTC, hishamco commented
@Piedone is there anything you need to add?

2024-04-14 23:23 UTC, Piedone approved these changes

2024-04-14 23:23 UTC, merged