User timezone caching #15536
OrchardCMS/OrchardCore pull request #15796
Opened 2024-04-20 07:39 UTC by KeithRaven

Fix for issue #15536

2024-04-20 07:41 UTC, hishamco commented
Fix the merge conflict

2024-04-20 07:43 UTC, hishamco requested changes

2024-04-20 07:43 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Users/TimeZone/Handlers/TimeZoneUserEventHandler.cs
> +internal class TimeZoneUserEventHandler : UserEventHandlerBase
```suggestion

public class TimeZoneUserEventHandler : UserEventHandlerBase
```

2024-04-20 07:43 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Users/TimeZone/Handlers/TimeZoneUserEventHandler.cs
> +    }
```suggestion
    public override async Task DeletedAsync(UserDeleteContext context)
        => await _userTimeZoneService.UpdateUserTimeZoneAsync(context.User);
```

2024-04-20 07:43 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Users/TimeZone/Handlers/TimeZoneUserEventHandler.cs
> +    }
```suggestion
    public override async Task UpdatedAsync(UserUpdateContext context)
        => await _userTimeZoneService.UpdateUserTimeZoneAsync(context.User);
```

2024-04-20 08:16 UTC, KeithRaven commented
Switched to draft as there's still a point for discussion in the linked issue.

2024-04-20 08:16 UTC, KeithRaven commented on src/OrchardCore.Modules/OrchardCore.Users/TimeZone/Handlers/TimeZoneUserEventHandler.cs
> +internal class TimeZoneUserEventHandler : UserEventHandlerBase
Thanks updated

2024-06-20 02:51 UTC, hishamco commented
@KeithRaven is this something you will revise soon?

2024-08-15 17:43 UTC, MikeAlhayek commented
for instructions on how to resolve the merge conflicts due to #16572 please follow the step listed in [this comment](https://github.com/OrchardCMS/OrchardCore/issues/16572#issuecomment-2291836365).

2024-10-30 00:57 UTC, closed without merging

2024-10-30 17:40 UTC, hishamco commented
@deanmarcussen can we reopen this and accept this PR?

2024-10-31 20:46 UTC, KeithRaven commented
Apologies for letting this slide.  If I can get an opinion on the question I asked in the issue re appropriate absolute expiration time https://github.com/OrchardCMS/OrchardCore/issues/15536#issuecomment-2080427836 then I'll get this tidied up.

2024-10-31 20:58 UTC, deanmarcussen commented
conceptually fine, but code has since been refactored by someone else and the cache inside the `UserTimeZoneService` is now essentially useless, so the new issue is what really needs fixing (at which point this could be visited as the idea is good, but where it is, is no longer useful.)

refer : [#16392](https://github.com/OrchardCMS/OrchardCore/issues/16932)