Make YesSqlOptions configurable from configuration provider
OrchardCMS/OrchardCore pull request #16079
Opened 2024-05-16 23:18 UTC by MikeAlhayek

Fix #16006

2024-05-17 15:17 UTC, MikeAlhayek commented on src/OrchardCore.Cms.Web/appsettings.json
> +    //  "EnableThreadSafetyChecks": false
done

2024-05-17 15:17 UTC, MikeAlhayek commented on .github/workflows/mac_unit_test_ci.yml
> +        OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
I removed it and kept it to all databases tests only.

2024-05-17 15:27 UTC, MikeAlhayek commented on .github/workflows/mac_unit_test_ci.yml
Any idea how we can verify if the flag is being uses?

2024-05-17 15:28 UTC, Piedone commented on .github/workflows/mac_unit_test_ci.yml
You can make a `true` value throw an exception temporarily as a test.

2024-05-17 16:02 UTC, MikeAlhayek commented on .github/workflows/mac_unit_test_ci.yml
done and tests failed. so it is being used.

2024-05-17 17:29 UTC, Piedone commented on .github/workflows/mac_unit_test_ci.yml
> +        OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
These are needed in all workflows, but not in the Unit Tests but Functional Tests steps. You just need to move them a few lines lower.

2024-05-17 17:34 UTC, Piedone commented on .github/workflows/mac_unit_test_ci.yml
[This build](https://github.com/OrchardCMS/OrchardCore/actions/runs/9130747913/job/25108357143) wasn't an evidence of that, since unit, not functional tests failed, and those enable the option in a hard-coded way [here](https://github.com/OrchardCMS/OrchardCore/blob/5a45ac58fc5aa24dfca1a1cf0e14b45690be158e/test/OrchardCore.Tests/Apis/Context/SiteStartup.cs#L33).

You need to run the functional tests [here](https://github.com/OrchardCMS/OrchardCore/actions/workflows/functional_all_db.yml):

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/e1a3f70c-b882-4f09-9798-fd946abbd5e7)

Or, temporarily remove the Unit Tests step from the `pr_ci` workflow and after [re-adding the config for the Functional Tests step there](https://github.com/OrchardCMS/OrchardCore/pull/16079#discussion_r1605352678) the next push will show if it works.

2024-05-17 17:34 UTC, Piedone requested changes

2024-05-17 17:34 UTC, Piedone commented on .github/workflows/functional_all_db.yml
> +      OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
Also set it for SQLite.

2024-05-18 00:19 UTC, MikeAlhayek commented on .github/workflows/functional_all_db.yml
> +      OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
done

2024-05-18 00:19 UTC, MikeAlhayek commented on .github/workflows/mac_unit_test_ci.yml
done

2024-05-18 17:25 UTC, Piedone approved these changes
I guess this was ready for another review :).

2024-05-18 17:34 UTC, merged