Use TextArea in MarkdownField By Default
OrchardCMS/OrchardCore pull request #16189
Opened 2024-05-29 00:31 UTC by MikeAlhayek

Fix #12318

2024-05-29 22:08 UTC, Piedone requested changes

2024-05-29 22:08 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
While this is technically a breaking change, the default editor being different shouldn't bother anyone. However, we do need to offer a migration path if people previously configured the Multi-line editor.

Very strange, but I get this though, which completely breaks the app. Ideally, the user wouldn't need to do anything and the Standard editor would be used. As an acceptable alternative, we can instruct them to switch to the Standard one by hand before trying to use the field. It shouldn't make the app fail to load, though.

1. Add a Markdown Field to Blog Post on the `main` code.
2. Configure it for Multi-line.
3. Switch to this branch.
4. The app fails to start with the below exceptions. Switching back to `main` fixes the issue.

```
2024-05-29 23:58:56.9432|None|00-25e20b9cf847f3150b8b5419af056fda-1214f0e5c1c5b899-00|1|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Twitter, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.) (Could not load file or assembly 'Microsoft.Extensions.Caching.StackExchangeRedis, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.) (Could not load file or assembly 'Microsoft.AspNetCore.Authentication.OpenIdConnect, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.Twitter, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Authentication.Twitter, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at OrchardCore.Environment.Extensions.ExtensionManager.<>c__DisplayClass31_0.<EnsureInitialized>b__0(Module module, ParallelLoopState cancellationToken) in E:\Projects\OrchardForks\OrchardCore5\src\OrchardCore\OrchardCore\Extensions\ExtensionManager.cs:line 300
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Caching.StackExchangeRedis, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Caching.StackExchangeRedis, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at OrchardCore.Environment.Extensions.ExtensionManager.<>c__DisplayClass31_0.<EnsureInitialized>b__0(Module module, ParallelLoopState cancellationToken) in E:\Projects\OrchardForks\OrchardCore5\src\OrchardCore\OrchardCore\Extensions\ExtensionManager.cs:line 300
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.OpenIdConnect, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Authentication.OpenIdConnect, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at OrchardCore.Environment.Extensions.ExtensionManager.<>c__DisplayClass31_0.<EnsureInitialized>b__0(Module module, ParallelLoopState cancellationToken) in E:\Projects\OrchardForks\OrchardCore5\src\OrchardCore\OrchardCore\Extensions\ExtensionManager.cs:line 300
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

2024-05-29 22:08 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
Add a note to the release notes.

2024-05-29 22:27 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
Very strange. It should be a breaking changes and when I tried it before submitting the PR it worked with no issue. The Editor is an alternate and should just be ignored if there is no matching view found.

The error seems strange as if your dlls did not build correctly. Did you try cleaning your project using "npm run cleanup" or anything other way? 

I'll try to recreate the issue when time permits.

2024-05-29 22:46 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
Hmm, now I cleaned the repo and did the same, plus quit VS when switching the branch. This fixed the issue and the field otherwise works too.

2024-05-30 02:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
So nothing to do here, right? If so please resolve the comment

2024-05-30 03:50 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
notes have been added.

2024-05-30 08:24 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.Markdown/Views/MarkdownField-TextArea.Edit.cshtml
I did at that time immediately.

2024-05-30 08:29 UTC, Piedone requested changes

2024-05-30 08:29 UTC, Piedone commented on src/docs/releases/2.0.0.md
> +W
```suggestion
Before this release, the `MarkdownField` used a single-line input field by default (named the Standard editor) and offered two different editors: Multi-line with a simple `textarea` and WYSIWYG with a rich editor. Now, by default, it uses a `textarea` as the Standard editor, and the separate Multi-line option has been removed.

You have nothing to do, fields configured with the Standard or Multi-line editors previously will both continue to work. Note though, that their editors will now be a `textarea`.
```

2024-05-30 08:31 UTC, Piedone commented
Feel free to merge if you just apply the code suggestion.

2024-05-30 16:00 UTC, merged