Add option to set CORS exposed headers
OrchardCMS/OrchardCore pull request #16258
Opened 2024-06-06 16:29 UTC by vsezima

fixes #16232

2024-06-06 17:15 UTC, MikeAlhayek requested changes

2024-06-06 17:15 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Cors/Controllers/AdminController.cs
> +                        ExposedHeaders = policySetting.ExposedHeaders
```suggestion
                        ExposedHeaders = policySetting.ExposedHeaders,
```

2024-06-06 17:15 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Cors/Controllers/AdminController.cs
> +                    ExposedHeaders = settingViewModel.ExposedHeaders
```suggestion
                    ExposedHeaders = settingViewModel.ExposedHeaders,
```

2024-06-06 17:15 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Cors/Services/CorsOptionsConfiguration.cs
> +                    if (corsPolicy.ExposedHeaders.Length > 0)
```suggestion
                    if (corsPolicy.ExposedHeaders?.Length > 0)
```

2024-06-06 17:15 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Cors/Views/Admin/Index.cshtml
> +        <div class="card mb-2">
```suggestion
        <div class="card mb-3">
```

2024-06-06 17:15 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Cors/Views/Admin/Index.cshtml
> +                <div class="">
```suggestion
                <div>
```

2024-06-06 18:12 UTC, sebastienros approved these changes

2024-06-06 18:13 UTC, hishamco commented
@vsezima waiting to CLA approval then I can merge

2024-06-06 18:19 UTC, MikeAlhayek approved these changes

2024-06-07 06:11 UTC, vsezima commented
@dotnet-policy-service agree company="PUXdesign"

2024-06-07 16:16 UTC, merged

2024-06-07 16:16 UTC, hishamco commented
Thanks for contribution @vsezima