Update NuGet references automatically once a week
OrchardCMS/OrchardCore pull request #16284
Opened 2024-06-11 02:23 UTC by sebastienros

This will create a single PR weekly with all the minor version updates for the referenced packages.
If we think that some of them should be updated less often, or with different rules (no patch version for instance), or not updated automatically, then we can add more groups.

These PRs also reference the release notes from each package update if available, which helps us understand what we are getting.

2024-06-11 23:17 UTC, Piedone requested changes
This is great, but we'll need to keep the src/docs/resources/libraries/README.md file up-to-date too. Doing that manually while the packages auto-update automatically wouldn't be fun.

I'm OK with just removing the version columns there; I was never a big fan of that page and its maintenance burden anyway. Or perhaps we can remove it altogether, since you can generate such an overview anyway (https://github.com/OrchardCMS/OrchardCore/issues/156049).

2024-06-12 01:09 UTC, sebastienros commented
Fine to remove the version, doesn't add much, the props file is a good repos for all the versions. This way we can keep the file, we don't add dependencies very often so it's low maintenance.

2024-06-12 04:25 UTC, Piedone requested changes

2024-06-12 04:25 UTC, Piedone commented on src/docs/resources/libraries/README.md
The Version column headers remained (check the file in preview).

2024-06-12 18:37 UTC, sebastienros commented on src/docs/resources/libraries/README.md
In these cases, hit '.', change the file, commit. It's even faster that commenting.
Or click Edit in the Files page, for simple changes.

2024-06-12 18:42 UTC, Piedone commented on src/docs/resources/libraries/README.md
I was on my phone where I definitely won't go and try edit Markdown tables :).

2024-06-12 18:43 UTC, Piedone approved these changes

2024-06-12 18:49 UTC, merged

2024-06-12 18:55 UTC, sebastienros commented on src/docs/resources/libraries/README.md
You need a new phone. Or an iPad with the cellular option