convert jsonDynamic to contentitem extension
OrchardCMS/OrchardCore pull request #16283
Opened 2024-06-10 11:49 UTC by giannik

resolves #16233

2024-06-10 11:50 UTC, giannik commented
@gvkries please review.

2024-06-10 14:17 UTC, gvkries commented
I think it is beneficial to add support for a generic `ToObject<T>` functionality back to `JsonDynamicObject` and probably `JsonDynamicValue` as well. This was possible with Newtonsoft and would avoid having a specialized extension method just for `ContentItem`. It would also solve problems like #16221.

It would look like in this example:
```csharp
@foreach (var foo in Model.ContentItem.Content.NamedBagPart.ContentItems)
{
    var contentItem = foo.ToObject<ContentItem>();
    ...
}
```
Note that this is actually possible right now, but only when using the `JsonObject` directly:
```csharp
@foreach (var foo in Model.ContentItem.Content.NamedBagPart.ContentItems)
{
    var contentItem = ((JsonObject)foo).ToObject<ContentItem>();
    ...
}
```
 We also have references to this style in the documentation, so we must fix it anyway IMHO.
https://github.com/OrchardCMS/OrchardCore/blob/7196b5b1c6c0180b17bb4dabe944232001b0a681/src/docs/reference/modules/Media/README.md?plain=1#L456

It would just require something like `public T? ToObject<T>() => _jsonObject.ToObject<T>();` in `JsonDynamicObject` and `JsonDynamicValue`, as there is an existing extension method for `JsonNode`.

2024-06-10 14:19 UTC, gvkries commented
I guess `JsonDynamicArray` must be considered as well.

2024-06-10 14:49 UTC, giannik commented
@gvkries feel free to make any changes.

2024-06-11 04:00 UTC, hishamco requested changes

2024-06-11 04:00 UTC, hishamco commented on src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentItemExtensions.cs
> +        }
```suggestion

        public static ContentItem ToContentItem(this JsonDynamicObject jsonDynamic)
        {
            var contentItem = new ContentItem();
            var contentProperties = jsonDynamic.ToString();
            contentItem.Merge(JObject.Parse(contentProperties));

            return contentItem;
        }
```

2024-06-11 11:05 UTC, gvkries commented
> @gvkries feel free to make any changes.

I don't think I have access to your PR :) I will open another PR with a different approach.

2024-06-11 12:18 UTC, gvkries commented
@giannik Please have a look at #16292...

2024-06-11 14:27 UTC, closed without merging

2024-06-11 14:27 UTC, giannik commented
closing in favor of  #16292