Fix dynamic field value issues
OrchardCMS/OrchardCore pull request #16294
Opened 2024-06-11 14:50 UTC by hyzx86

fixes #16290 
/cc @gvkries

2024-06-11 15:16 UTC, gvkries commented
This approach is not feasible IMHO, because you loose the dynamic behavior of `JsonDynamicValue` all together by returning just `string` or number. We should find a different way.

2024-06-11 15:29 UTC, hyzx86 commented on src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicValueWrapper.cs
> +public struct JsonDynamicValueWrapper<T>
Maybe refer to Nullable<T>, this experiment didn't work for me~

2024-06-11 16:22 UTC, gvkries commented
I think your problem is not in the dynamic wrappers itself, but the fact that they are serialized as well. In contrast to NSJ we now have a layer more, to support the dynamic behavior NSJ has by default. But when you serialize e.g. a `JsonDynamicValue`, you don't get the value only, like in NSJ, but the wrapper as well.
Maybe the solution is to add another `JsonConverter` for these dynamic wrappers, which will skip them and serialize the containing JSON only. I mean something like:
```csharp
public override void Write(
    Utf8JsonWriter writer,
    object objectToWrite,
    JsonSerializerOptions options)
{
    if (objectToWrite is JsonDynamicValue value && value.JsonValue != null)
    {
        value.JsonValue.WriteTo(writer, options);
    }
    else
    {
        JsonSerializer.Serialize(writer, objectToWrite, objectToWrite.GetType(), options);
    }

```

2024-06-11 16:35 UTC, hyzx86 commented
Like the following unit test, actually in version 1.8 we can use `contentItem2.Content.MyPart.myField.Value.FullYear` directly in the js if I remember correctly.

It looks like if we have to use STJ in 2.0, we'll have to give up a few things.
 
```c#
            var contentItem2 = JConvert.DeserializeObject<ContentItem>(json);
            Assert.Equal(new DateTime(2024, 1, 1, 10, 42, 0, DateTimeKind.Utc), (DateTime?)contentItem2.Content.MyPart.myField.Value);
```

2024-06-11 16:50 UTC, hyzx86 commented on src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicObject.cs
> +                    if(jsonValue.TryGetValue<DateTime>(out var datetime))
I've added some type conversion tests here，If this scenario is acceptable, perhaps we need to add some abstraction converters for some custom development scenarios

2024-06-12 05:27 UTC, hishamco requested changes

2024-06-12 05:27 UTC, hishamco commented on src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicObject.cs
> +            }
```suggestion
            switch (valueKind)
            {
                case JsonValueKind.String:
                    if (jsonValue.TryGetValue<DateTime>(out var datetime))
                    {
                        return _dictionary[key] = datetime;
                    }
                    
                    if (jsonValue.TryGetValue<TimeSpan>(out var timeSpan))
                    {
                        return _dictionary[key] = timeSpan;
                    }
                    
                    return _dictionary[key] =  jsonValue.GetString();
                case JsonValueKind.Number:
                    return _dictionary[key] = jsonValue.GetNumber();
                case JsonValueKind.True:
                    return _dictionary[key] = true;
                case JsonValueKind.False:
                    return _dictionary[key] = false;
            }
```

2024-06-12 05:27 UTC, hishamco commented on test/OrchardCore.Tests/Data/JsonDynamicTests.cs
> +    }
```suggestion

    public class TestPart : ContentPart
    {
        public TextField TextFeildProp { get; set; }

        public NumericField NumericFieldProp { get; set; }

        public BooleanField BooleanFieldProp { get; set; }

        public TimeField TimeFieldProp { get; set; }

        public DateTimeField DateTimeFieldProp { get; set; }
    }
```

2024-06-12 05:27 UTC, hishamco commented on test/OrchardCore.Tests/Data/JsonDynamicTests.cs
> +        var contentItem = new ContentItem();
```suggestion
       // Arrange
        var contentItem = new ContentItem();
```

2024-06-12 05:27 UTC, hishamco commented on test/OrchardCore.Tests/Data/JsonDynamicTests.cs
> +        dynamic expandoValue = new ExpandoObject();
```suggestion
        // Act
        dynamic expandoValue = new ExpandoObject();
```

2024-06-12 05:27 UTC, hishamco commented on test/OrchardCore.Tests/Data/JsonDynamicTests.cs
> +        var jsonStr = JConvert.SerializeObject((ExpandoObject)expandoValue);
```suggestion
       // Assert
        var jsonAsString = JConvert.SerializeObject((ExpandoObject)expandoValue);
```

2024-06-12 05:27 UTC, hishamco commented on test/OrchardCore.Tests/Data/JsonDynamicTests.cs
> +        Assert.Equal("{\"stringValue\":\"test\",\"numberValue\":123,\"booleanValue\":true,\"timeValue\":\"12:12:23\",\"dateTimeValue\":\"2024-06-12T00:43:00Z\"}", jsonStr);
```suggestion
        Assert.Equal("{\"stringValue\":\"test\",\"numberValue\":123,\"booleanValue\":true,\"timeValue\":\"12:12:23\",\"dateTimeValue\":\"2024-06-12T00:43:00Z\"}", jsonAsString);
```

2024-06-12 06:18 UTC, hyzx86 commented on src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicObject.cs
> +                    if (jsonValue.TryGetValue<DateTime>(out var datetime))
This is actually an unsafe practice, as if the user happens to save a date value in a `TextField.Text`, it may be recognised as a date type

2024-06-12 07:39 UTC, hyzx86 commented on src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/DefaultJsonDyanmicValueHandler.cs
> +                    if (memberName == "Value")
If I remember correctly the only two types of fields that currently take values from strings in OC seem to be these two types, which are always wrapped in Value

2024-06-12 07:41 UTC, gvkries commented
If I understand your approach correctly, you are moving parts of the value conversions from `JsonDynamicValue` to `JsonDynamicObject`. This is different from the current design, where we have the separation of value functionality and Json objects + arrays. One can argue that the `JsonDynamicValue` is not necessary, but I would not change that at this stage. 

In summary, I strongly suggest to keep the current separation of value and object. Don't add conversion functionality into the `JsonDynamicObject` class at all.

2024-06-12 07:41 UTC, hyzx86 commented on src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicObject.cs
> +        foreach (var handler in JsonDynamicConfigurations.ValueHandlers)
Added a static collection to handle dynamic values for custom development environments

2024-06-12 07:41 UTC, hyzx86 commented on src/OrchardCore/OrchardCore.Abstractions/Json/Serialization/ServiceCollectionExtensions.cs
> +    public static IServiceCollection AddJsonDynamicValueHandler<T>(this IServiceCollection services) where T : IJsonDynamicValueHandler, new()
自定义取值逻辑可以在这里添加

2024-06-12 07:47 UTC, hyzx86 commented
> If I understand your approach correctly, you are moving parts of the value conversions from `JsonDynamicValue` to `JsonDynamicObject`. This is different from the current design, where we have the separation of value functionality and Json objects + arrays. One can argue that the `JsonDynamicValue` is not necessary, but I would not change that at this stage. 

Okay, if we have to do that, it's not impossible, we may have to pass the MemberName to the `JsonDynamicValue` object Mainly as I mentioned above, we can't rely on the code alone to detect the value in a way that determines the target type
https://github.com/OrchardCMS/OrchardCore/pull/16294#discussion_r1635873438

2024-06-12 09:33 UTC, gvkries commented
> Okay, if we have to do that, it's not impossible, we may have to pass the MemberName to the `JsonDynamicValue` object Mainly as I mentioned above, we can't rely on the code alone to detect the value in a way that determines the target type [#16294 (comment)](https://github.com/OrchardCMS/OrchardCore/pull/16294#discussion_r1635873438)

I don't understand exactly what you mean by that, but I think we don't have to do a lot beside #16292. I'll add custom `JsonConverter` for the dynamic wrappers, to ensure they will not be serialized. This will almost be what you want. E.g. your test will pass after those changes:

```csharp
[Fact]
    public void TestDynamicValueAssignToOther()
    {
        var contentItem = new ContentItem();
        contentItem.Alter<TestPart>(part =>
        {
            part.TextFieldProp = new TextField { Text = "test" };
            part.NumericFieldProp = new NumericField { Value = 123 };
            part.BooleanFieldProp = new BooleanField { Value = true };
        });

        dynamic expandoValue = new ExpandoObject();
        expandoValue.stringValue = contentItem.Content.TestPart.TextFieldProp.Text;
        expandoValue.numberValue = contentItem.Content.TestPart.NumericFieldProp.Value;
        expandoValue.booleanValue = contentItem.Content.TestPart.BooleanFieldProp.Value;

        var jsonStr = JConvert.SerializeObject((ExpandoObject)expandoValue);
        Assert.Equal("{\"stringValue\":\"test\",\"numberValue\":123,\"booleanValue\":true}", jsonStr);
    }
```

Note that we decided to not bring back support for `.Value`. Therefore the following example will not work without casting to `DateTime`: `contentItem2.Content.MyPart.myField.Value.FullYear`. This example is also wrong for NSJ, there you also needed to get the strongly typed value by accessing it like `contentItem2.Content.MyPart.myField.Value.Value.FullYear` (note the second `Value`). This `Value` will be a `DateTime` in NSJ, but in STJ we don't have that type information. I think we can ignore that and force users to cast to a strongly typed value, if they require it. Otherwise the `JsonDynamicValue` class will get too complex I think (it already is a mess).

2024-06-12 09:40 UTC, hyzx86 commented
If we don't seem to have a way to ask the user to force a type conversion in Jint
Jint use `ExpandoObject` ， That's why I use ExpandoObject to wrap the object in the test

2024-06-12 09:46 UTC, gvkries commented
But it should be almost the same as with NSJ now. Only `.Value` is missing and can be replaced with a cast.

2024-06-12 09:47 UTC, gvkries commented
Please check #16292 again if it is enough for you.

2024-06-12 10:22 UTC, hyzx86 commented
> Please check #16292 again if it is enough for you.

Thanks, but I still need to verify the difference between it and NSJ in Jint to make sure I don't have any more problems with my existing programmes.

I need some time to verify them.

2024-06-12 18:47 UTC, closed without merging