Added option to select the Target in Link Field
OrchardCMS/OrchardCore pull request #16326
Opened 2024-06-15 17:51 UTC by vengi83644

![image](https://github.com/OrchardCMS/OrchardCore/assets/5276778/5b9317a3-03c2-4deb-abe1-99d40e294ea1)

![image](https://github.com/OrchardCMS/OrchardCore/assets/5276778/9462303d-72a1-414f-a9fa-bd8ef94bac19)

2024-06-15 17:52 UTC, vengi83644 commented
https://github.com/OrchardCMS/OrchardCore/issues/16244

2024-06-16 00:12 UTC, MikeAlhayek requested changes

2024-06-16 00:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/LinkFieldIndexProvider.cs
> +                                Target = pair.Field.Target
```suggestion
                                Target = pair.Field.Target,
```

2024-06-16 00:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Views/LinkField.Edit.cshtml
> +                        <option value="_self">@T["Opens the linked document in the same frame as it was clicked (this is default)."]</option>
```suggestion
                        <option value="_self">@T["Opens the linked document in the same frame as it was clicked (default)."]</option>
```

2024-06-16 00:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Views/LinkField.Edit.cshtml
> +                            target
```suggestion
                            @T["Target"]
```

2024-06-16 00:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Views/LinkFieldSettings.Edit.cshtml
> +</div>
```suggestion
</div>

```

2024-06-16 00:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Views/LinkFieldSettings.Edit.cshtml
> +            <option value="_self">@T["Opens the linked document in the same frame as it was clicked (this is default)."]</option>
```suggestion
            <option value="_self">@T["Opens the linked document in the same frame as it was clicked (default)."]</option>
```

2024-06-16 00:12 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Views/LinkField.cshtml
> +    var target = !string.IsNullOrWhiteSpace(Model.Target) ? Model.Target : "";
```suggestion
    var target = !string.IsNullOrWhiteSpace(Model.Target) ? Model.Target : "_self";
```

2024-06-16 11:33 UTC, hishamco requested changes

2024-06-16 11:33 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.ContentFields/Views/LinkField.Edit.cshtml
> +                        @T["The target attribute of the A tag, see more:"]
```suggestion
                        @T["The target attribute of the anchor tag, see more:"]
```

2024-06-16 11:50 UTC, hishamco approved these changes

2024-06-16 11:51 UTC, hishamco commented
@MikeAlhayek waiting for your approval or I will merge tonight

2024-06-16 18:00 UTC, MikeAlhayek approved these changes

2024-06-16 18:01 UTC, merged

2024-06-25 19:34 UTC, sebastienros commented
Don't we need to update the migration if there is a new field in the index table?
Do we really need to index link targets? Is there any business need to query links by their html target?

2024-06-26 08:41 UTC, vengi83644 commented
We had a situation where we wanted to know how and where we used external links in our pages. One example page is this https://worldatwork.org/events

I missed the migrations. I will create a PR soon.

2024-07-02 16:42 UTC, sebastienros commented
I feel like this is mixing business and ui logic. I would assume these kind of links are specific to a very special kind of entity it's describing, and the fact this external link is opening in a new window is just based on this flag. For instance, a "Vendor" could be "External" and based on that the link to the vendor should use a "_blank" link.

This not only would feel right (ok this is a personal opinion) but this would not require this "niche" feature (indexing UI values). Otherwise this opens us to accepting everything in the index.

2024-07-02 16:52 UTC, sebastienros commented
@vengi83644 just to try to prove my point, where in your site, as a user, do I see the list of the things that are filtered by this new indexed value? Like is there a page of specific things that open in _blank, or a checkbox/filter for that?

2024-07-02 17:40 UTC, MikeAlhayek commented
@sebastienros I think we should have the Target as settings but there is no need for indexing it.

2024-07-03 03:28 UTC, vengi83644 commented
@sebastienros @MikeAlhayek @Piedone We let our content authors get reports from the CMS for various use cases - examples: contents using certain widgets, certain content types with their title and description, contents of widgets used in different content types, a typical SEO report. Below is the screenshot of the page,
![image](https://github.com/OrchardCMS/OrchardCore/assets/5276778/cf5f2c91-c55e-4dfc-8955-79e6660d4435)

I am OK with removing the field from the index as it's not a use case for the larger audience. Thanks.

2024-07-03 10:40 UTC, Piedone commented
OK, thanks, we're removing it, then. Please follow Sebastien's above recommendations instead.