Fixes that type/feature mappings are not available during setup
OrchardCMS/OrchardCore pull request #16324
Opened 2024-06-14 14:47 UTC by gvkries

This reverts some of the changes made by #15793. Especially, the population of the `ITypeFeatureProvider` was completley moved into the `ShellContainerFactory`. But this is too late e.g. for the `CompositionStrategy` which already requires some types being populated.

So I've moved that part back to the `ExtensionManager`, where it originally was done before #15793. This does not change the new behavior of having multiple features per type or the automatic detection of the feature without the `FeatureAttribute`, but the split responsibility of adding types to the `ITypeFeatureProvider` is now back.

Fixes #16289

2024-06-14 21:27 UTC, Piedone reviewed
This looks OK to me, but I'm out of my depth here so would defer to others.

This indeed fixed the symptoms of https://github.com/OrchardCMS/OrchardCore/issues/16289. What exactly in the changes fixes that BTW? What got stuck in App_Data after not running the setup?

2024-06-14 21:28 UTC, Piedone approved these changes

2024-06-18 08:06 UTC, hishamco requested changes

2024-06-18 09:24 UTC, gvkries commented on test/OrchardCore.Tests/Extensions/ExtensionManagerTests.cs
> +                new TypeFeatureProvider(),
No, it must be independent per extension manager.

2024-06-27 18:00 UTC, sebastienros approved these changes

2024-06-27 20:38 UTC, merged