Fixes that the media library uses the wrong file extensions
OrchardCMS/OrchardCore pull request #16449
Opened 2024-07-17 09:06 UTC by gvkries

If you use more than one media field for a content type with different file extension settings, the media library won't adjust to the different settings.

This was bugging me and the issue is already mentioned several times. So I added a quick fix to the existing media library app, although @Skrypt has a complete overhaul in the works in #14256. 

Fixes #15569
Fixes #16440

/cc @Skrypt

2024-07-17 22:02 UTC, Piedone requested changes

2024-07-17 22:03 UTC, Piedone commented
Would you like to also check, @yqzhen1990 @automatedChaos?

2024-07-18 08:03 UTC, gvkries commented on src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/app.js
True, I saw that, but forgot 🙈

2024-07-18 08:43 UTC, gvkries commented on src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/app.js
Done.

2024-07-18 17:20 UTC, Piedone approved these changes

2024-07-18 17:29 UTC, merged