Improving the Jean-Thierry Kéchichian Community Award docs page and adding Hisham
OrchardCMS/OrchardCore pull request #16728
Opened 2024-09-16 14:39 UTC by Piedone

2024-09-16 15:52 UTC, hishamco requested changes

2024-09-16 15:52 UTC, hishamco commented on src/docs/community/jean-thierry-community-award/README.md
> +- Ask community members to nominate people in public under the discussion board with a pinned discussion, linked from a pinned issue. Keep it nominations open for two weeks. Example [issue](https://g
```suggestion
- Ask community members to nominate people in public under the discussion board with a pinned discussion, linked from a pinned issue. Keep nominations open for two weeks. Example [issue](https://github.com/OrchardCMS/OrchardCore/issues/16555) and [discussion](https://github.com/OrchardCMS/OrchardCore/discussions/16553). Announce this on social media, Discord.
```

2024-09-18 16:32 UTC, Piedone commented
Anything else, or can we merge, @hishamco?

2024-09-18 18:21 UTC, hishamco requested changes

2024-09-18 18:21 UTC, hishamco commented on src/docs/community/jean-thierry-community-award/README.md
> +If your company works with Orchard Core and would like to incentivize community members, please let us know about what else you can add!
```suggestion
- Post about it under the Orchard Core social media.
- [Lombiq](https://lombiq.com/) provides free custom domain usage on [DotNest](https://dotnest.com/), publicizing the winner in Lombiq's media, and a year of sponsorship similar to [other open source contributors and projects](https://lombiq.com/open-source).

If your company works with Orchard Core and would like to incentivize community members, please let us know what else you can add!
```

2024-09-18 19:49 UTC, hishamco approved these changes

2024-09-18 20:10 UTC, merged