Adding content item alternates based on the alias
OrchardCMS/OrchardCore pull request #16722
Opened 2024-09-13 23:05 UTC by barthamark

Fixes #2866

2024-09-14 00:19 UTC, sebastienros approved these changes

2024-09-16 20:26 UTC, Piedone requested changes
I didn't review the PR after Sebastien, but am only adding the release notes note.

2024-09-16 20:26 UTC, Piedone commented on src/docs/reference/modules/Templates/README.md
Please add a note about this to https://github.com/OrchardCMS/OrchardCore/blob/main/src/docs/releases/2.1.0.md. See https://docs.orchardcore.net/en/latest/guides/contributing/contributing-documentation/.

2024-09-28 09:46 UTC, barthamark commented on src/docs/reference/modules/Templates/README.md
I added a note but I'm not sure if it's in the proper section, someone please confirm.

2024-09-28 13:28 UTC, Piedone approved these changes

2024-09-28 13:35 UTC, merged

2024-10-05 00:37 UTC, MikeAlhayek commented on src/docs/releases/2.1.0.md
> +### Content Item Shape Alternates Based on Alias and Slug
This should have been added before line 74 since it it not a new feature