Move permissions to its own class to avoid module to module reference
OrchardCMS/OrchardCore pull request #16769
Opened 2024-09-20 07:47 UTC by hishamco

Fixes #16766

2024-11-21 20:57 UTC, MikeAlhayek commented
@hishamco please document the changes in this PR. We need to make sure that developers have a migration path from one class to another.

For example:

The `ManageAdminSettings` permission has been relocated from `AdminPermissions.ManageAdminSettings` to `PermissionsAdminSettings.ManageAdminSettings`.

This way developers have a reference to refer to if there are using these permissions into their project.

2024-11-29 18:02 UTC, MikeAlhayek commented
@hishamco to avoid keep resolving conflicts, please document the changes so we can finalizing it.

2025-01-25 01:05 UTC, hishamco commented
@MikeAlhayek seems you forgot to reply to my last comment, we need to finalize this

2025-01-25 02:30 UTC, MikeAlhayek reviewed
We can't just relocate things and expect developer to guess where the new destination is at.

Either we document everything that was removed and was not already marked obsolete. Or, obsolete what was not already obsolete and point the new one to the old one.

Recommendation: I think it's better to only remove the properties with the Obsolete attribute only (since you already did that.) For the permissions that were not already obsolete, instead, I would obsolete them in this release. However, point the obsolete static properties to the new permanent properties. This way developers will have an easy transition path. Then in v4, we can then remove the last obsolete permissions.

2025-01-25 02:30 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentLocalization/Permissions.cs
> -    public static readonly Permission LocalizeContent = new("LocalizeContent", "Localize content for others");
These have to be documented

2025-01-25 02:30 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ContentTypes/Permissions.cs
> -    public static readonly Permission ViewContentTypes = new("ViewContentTypes", "View content types.");
These too

2025-01-25 02:30 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Permissions.cs
> -    public static readonly Permission ManageRemoteClients = new("ManageRemoteClients", "Manage remote clients");
These too

2025-01-30 23:36 UTC, hishamco commented
While breaking in modules are allowed I make the old permissions as `Obsolete` as you suggested earlier

2025-01-31 00:10 UTC, MikeAlhayek requested changes
There are more.... please make sure you are not creating new static instance. Instead point the old property to the new instance.

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Localization/Permissions.cs
> +    public static readonly Permission ManageCultures = new("ManageCultures", "Manage supported culture");
```suggestion
    public static readonly Permission ManageCultures = LocalizationPermissions.ManageCultures;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/MediaCachePermissions.cs
> +    public static readonly Permission ManageAssetCache = new("ManageAssetCache", "Manage Asset Cache Folder");
```suggestion
    public static readonly Permission ManageAssetCache = MediaPermissions.ManageAssetCache;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +    public static readonly Permission ViewMedia = new("ViewMediaContent", "View media content in all folders", new[] { Permissions.ManageMediaFolder });
```suggestion
    public static readonly Permission ViewMedia = MediaPermissions.ViewMedia;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +    public static readonly Permission ViewRootMedia = new("ViewRootMediaContent", "View media content in the root folder", new[] { ViewMedia });
```suggestion
    public static readonly Permission ViewRootMedia = MediaPermissions.ViewRootMedia;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +    public static readonly Permission ViewOthersMedia = new("ViewOthersMediaContent", "View others media content", new[] { Permissions.ManageMediaFolder });
```suggestion
    public static readonly Permission ViewOthersMedia = MediaPermissions.ViewOthersMedia;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +    public static readonly Permission ViewOwnMedia = new("ViewOwnMediaContent", "View own media content", new[] { ViewOthersMedia });
```suggestion
    public static readonly Permission ViewOwnMedia = MediaPermissions.ViewOwnMedia;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +                    MediaPermissions.ViewOthersMedia
```suggestion
                    MediaPermissions.ViewOthersMedia,
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +                    MediaPermissions.ViewOwnMedia
```suggestion
                    MediaPermissions.ViewOwnMedia,
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Media/SecureMediaPermissions.cs
> +                    MediaPermissions.ViewMedia
```suggestion
                    MediaPermissions.ViewMedia,
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.OpenId/Permissions.cs
>      public static readonly Permission ManageApplications
Please assign the old properties to the new static properties instead of creating a new instance.

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ReCaptcha/Permissions.cs
> +    public static readonly Permission ManageReCaptchaSettings = new("ManageReCaptchaSettings", "Manage ReCaptcha Settings");
```suggestion
    public static readonly Permission ManageReCaptchaSettings = ReCaptchaPermissions.ManageReCaptchaSettings;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Recipes/RecipesPermissionProvider.cs
> +    public static readonly Permission ManageReCaptchaSettings = new("ManageReCaptchaSettings", "Manage ReCaptcha Settings");
```suggestion
    public static readonly Permission ManageReCaptchaSettings = RecipePermissions.ManageRecipes;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Search.Lucene/LuceneIndexPermissionHelper.cs
> +    public static readonly Permission ManageLuceneIndexes = new("ManageLuceneIndexes", "Manage Lucene Indexes");
```suggestion
    public static readonly Permission ManageLuceneIndexes = LuceneSearchPermissions.ManageLuceneIndexes;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Search.Lucene/Permissions.cs
> +    [Obsolete("This will be removed in a future release. Instead use 'LuceneSearchPermissions.ManageLuceneIndexes'.")]
all there should be pointing to the new properties instead of creating new objects

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Search/Permissions.cs
> +    public static readonly Permission QuerySearchIndex = new("QuerySearchIndex", "Query any index");
```suggestion
    public static readonly Permission QuerySearchIndex = SearchPermissions.QuerySearchIndex;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Search/Permissions.cs
> +    public static readonly Permission ManageSearchSettings = new("ManageSearchSettings", "Manage Search Settings");
```suggestion
    public static readonly Permission ManageSearchSettings = SearchPermissions.ManageSearchSettings;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Settings/Permissions.cs
> +    public static readonly Permission ManageSettings = new("ManageSettings", "Manage settings");
```suggestion
    public static readonly Permission ManageSettings = SettingsPermissions.ManageSettings;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Settings/Permissions.cs
> +    public static readonly Permission ManageGroupSettings = new("ManageResourceSettings", "Manage settings", new[] { ManageSettings });
```suggestion
    public static readonly Permission ManageGroupSettings = SettingsPermissions.ManageGroupSettings;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Shortcodes/Permissions.cs
> +    public static readonly Permission ManageShortcodeTemplates = new("ManageShortcodeTemplates", "Manage shortcode templates", isSecurityCritical: true);
```suggestion
    public static readonly Permission ManageShortcodeTemplates = ShortcodesPermissions.ManageShortcodeTemplates;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Sitemaps/Permissions.cs
> +    public static readonly Permission ManageSitemaps = new("ManageSitemaps", "Manage sitemaps");
```suggestion
    public static readonly Permission ManageSitemaps = SitemapsPermissions.ManageSitemaps;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Workflows/Permissions.cs
> +    public static readonly Permission ManageWorkflows = new("ManageWorkflows", "Manage workflows", isSecurityCritical: true);
```suggestion
    public static readonly Permission ManageWorkflows = WorkflowsPermissions.ManageWorkflows;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Workflows/Permissions.cs
> +    public static readonly Permission ExecuteWorkflows = new("ExecuteWorkflows", "Execute workflows", isSecurityCritical: true);
```suggestion
    public static readonly Permission ExecuteWorkflows = WorkflowsPermissions.ExecuteWorkflows;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Workflows/Permissions.cs
> +    public static readonly Permission ManageWorkflowSettings = new("ManageWorkflowSettings", "Manage workflow settings", [ManageWorkflows]);
```suggestion
    public static readonly Permission ManageWorkflowSettings = WorkflowsPermissions.ManageWorkflowSettings;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Permissions.cs
> +    public static readonly Permission ApiViewContent = new("ApiViewContent", "Access view content endpoints");
```suggestion
    public static readonly Permission ApiViewContent = GraphQLPermissions.ApiViewContent;
```

2025-01-31 00:10 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.Email.Core/Permissions.cs
> +    public static readonly Permission ManageEmailSettings = new("ManageEmailSettings", "Manage Email Settings");
```suggestion
    public static readonly Permission ManageEmailSettings = EmailPermissions.ManageEmailSettings;
```

2025-01-31 00:21 UTC, hishamco commented
> There are more.... please make sure you are not creating new static instance. Instead point the old property to the new instance.

Pointing out old properties is useless because if we use them a warning will show up, let me double-check after finalizing another PR

2025-01-31 00:42 UTC, MikeAlhayek commented
@hishamco how is it useless?

This will create new allocations for the life of the app.

Also recently @gvkries push a PR that will log errors if there are any duplicate permissions. In your case, you may encounter duplicate errors.

2025-01-31 00:52 UTC, hishamco commented
Do you mean this #17430?

2025-01-31 04:36 UTC, MikeAlhayek approved these changes
@hishamco please ensure the following is confirmed and done before merging

1. Resolve the last suggestions
2. Make sure the new permission classes are located in the core project if a core project exists. 
3. Make sure you did not change any of the permissions. Confirm that you just moved them into a different class as-is.


If the above is confirmed done, feel free to merge.

Thank you

2025-01-31 04:36 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.ReCaptcha/Permissions.cs
> +
```suggestion

```

2025-01-31 04:36 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.Search.AzureAI.Core/AzureAISearchPermissions.cs
> +
```suggestion
```

2025-01-31 04:36 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.Search.Elasticsearch.Core/ElasticsearchPermissions.cs
> +
```suggestion
```

2025-01-31 04:36 UTC, MikeAlhayek commented on src/OrchardCore/OrchardCore.Seo.Abstractions/SeoPermissions.cs
> +namespace OrchardCore.Seo;
```suggestion
namespace OrchardCore.Seo;

```

2025-01-31 19:57 UTC, hishamco commented
@MikeAlhayek hopefully everything is ok, I just created `UserPermissions` & `RolesPermissions` to make everything consistent, feel free to merge or I will merge later

2025-01-31 20:37 UTC, MikeAlhayek commented
I am good with the last change. If you are done, feel free to merge it.

2025-01-31 20:59 UTC, merged