Don't use JObject.Merge in OpenId module
OrchardCMS/OrchardCore pull request #16865
Opened 2024-10-10 21:27 UTC by hishamco

2024-10-10 21:34 UTC, hishamco commented
Oops seems one of the unit tests has broken :(

2024-10-10 21:37 UTC, MikeAlhayek requested changes
Please be sure to test out changes before submitting a PR to ensure the changes actually solve the problem. As of this review, I am confident that the issue still exists.

2024-10-10 21:37 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.OpenId/Deployment/OpenIdServerDeploymentSource.cs
>              ["name"] = nameof(OpenIdServerSettings),
name should be `Settings`

2024-10-10 21:37 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.OpenId/Deployment/OpenIdValidationDeploymentSource.cs
> +            ["name"] = nameof(OpenIdValidationSettings),
```suggestion
            ["name"] = "Settings",
```

2024-10-10 23:04 UTC, MikeAlhayek commented
https://github.com/OrchardCMS/OrchardCore/pull/16862#issuecomment-2406177957

It is a test bug because now you changed how we export and import the settings "it was not working before" so the test was wrong

2024-10-11 04:30 UTC, MikeAlhayek approved these changes

2024-10-11 07:00 UTC, merged