Elasticsearch geo location type addition
OrchardCMS/OrchardCore pull request #16880
Opened 2024-10-14 03:47 UTC by PBMikeW

Add switch statement and dynamic template for GeoPoint -> geo_point. Uses search pattern of *.Location as GeoPointFieldIndexHandler forces an index as "Location"

Mapping:
      "dynamic_templates": [
        {
          "*.Location": {
            "path_match": "*.Location",
            "match_mapping_type": "object",
            "mapping": {
              "type": "geo_point"
            }
          }
        }
      ],

Query:
{
  "query": {
    "bool": {
      "must": [
        {
          "geo_bounding_box": {
            "ContentTypeName.Location": {
              "top_left": {
                "lat": -34.0,
                "lon": 166.0
              },
              "bottom_right": {
                "lat": -40.0,
                "lon": 179.0
              }
            }
          }
        }
      ]
    }
  }
}

2024-10-14 03:49 UTC, PBMikeW commented
@Skrypt

2024-10-15 01:04 UTC, Skrypt commented
Will review

2024-10-15 23:25 UTC, Skrypt commented on src/OrchardCore/OrchardCore.Search.Elasticsearch.Core/Services/ElasticIndexManager.cs
> +                        AddValue(entries, entry.Name, new GeoLocation((double)point.Latitude, (double)point.Longitude));
Use long for accuracy?

2024-10-15 23:29 UTC, Skrypt approved these changes

2024-10-17 05:46 UTC, hishamco requested changes

2024-10-17 05:46 UTC, hishamco commented on src/OrchardCore/OrchardCore.Search.Elasticsearch.Core/Services/ElasticIndexManager.cs
> +                    break;
```suggestion

                    break;
```

2024-10-17 05:46 UTC, hishamco commented on src/OrchardCore/OrchardCore.Search.Elasticsearch.Core/Services/ElasticIndexManager.cs
> +                        .GeoPoint(g => g))
```suggestion
                    .Mapping(m => m.GeoPoint(g => g))
```

2024-10-17 21:53 UTC, hishamco approved these changes

2024-10-17 22:04 UTC, merged