Fix elasticsearch NRE when no results are found.
OrchardCMS/OrchardCore pull request #16919
Opened 2024-10-21 20:05 UTC by PBMikeW

When no results are found from elasticsearch query, TopDocs returns null and the where clause causes an NRE. Add check for count and TopDocs and return early.

2024-10-29 02:58 UTC, Skrypt commented
Does it make any performance difference? That's the only thing I can see there. I don't think the actual code would return any NRE.

2024-10-29 03:55 UTC, PBMikeW commented
> I don't see how this will solve an NRE problem. In current code, the `elasticQueryResults.Items` is being set in the if and in the else conditions so it would never be null. Can you please file an issue and link this PR to it so we can understand the problem?

Seems it only NRE's when the query has an error in it (Something I hit a _LOT_ when converting from lucene)
![image](https://github.com/user-attachments/assets/bdbbda7f-70c5-4d8c-a8bc-16d504ed2182)

Because of this a good error does not propagate to the front end.

2024-10-29 03:59 UTC, Skrypt commented
Ok then, create a ticket with this issue and this screenshot and let's try to make this error shown on the UI instead. That's what it should do. Normally it should. And please provide the ElasticSearch Query example.

2024-10-30 03:59 UTC, Skrypt commented
Created here: https://github.com/OrchardCMS/OrchardCore/issues/16938

2024-10-30 04:00 UTC, Skrypt requested changes
I do not approve this PR as it is not the proper fix.

2024-10-30 19:15 UTC, PBMikeW commented
> I do not approve this PR as it is not the proper fix.
@Skrypt Should I put the effort in to get the error to the UI?

2024-10-31 17:42 UTC, sebastienros approved these changes

2024-10-31 17:42 UTC, merged

2024-10-31 17:42 UTC, sebastienros commented
Fixes #16938

2024-10-31 20:27 UTC, Skrypt commented
We could have used the notifier for that matter.

2024-10-31 20:30 UTC, PBMikeW commented
> We could have used the notifier for that matter.

Digging with this now, letting the error bubble up gives a nice error in ui.
![image](https://github.com/user-attachments/assets/0e3f3347-d8f5-4c4e-b00c-5fb77d6a8afd)

However the razor helper and api error now, might have to swallow the error here. (May stop a page loading)
![image](https://github.com/user-attachments/assets/0405af67-81ac-430a-98df-0339b8090063)

2024-10-31 20:34 UTC, Skrypt commented
Thanks for doing this 👍🏼 
@sebastienros doesn't trust me 😉 🐰

2024-10-31 20:42 UTC, Skrypt commented
On frontend it is expected that if the Query is wrong that the page fails.
I'd rather log the error if that happens on frontend.

2024-10-31 20:50 UTC, PBMikeW commented
> On frontend it is expected that if the Query is wrong that the page fails. I'd rather log the error if that happens on frontend. So yeah, swallow it but log it.

Ok if I have this correct.
1)  Bubble the error up for the admin ui model
2) Razor and liquid helper swallow the error (Its already logged in Elastic Module)
3) Api return a problem?

Im in the Discord channel if you want to chat.

2024-10-31 20:51 UTC, Skrypt commented
Yeah, I don't think we have ProblemDetails on API requests. That's something we would eventually need.