Template content validation
OrchardCMS/OrchardCore pull request #16944
Opened 2024-11-01 21:14 UTC by sarahelsaig

Fixes #16943

2024-11-02 08:54 UTC, hishamco requested changes

2024-11-02 08:54 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Templates/Controllers/TemplateController.cs
> +            var docsLink = "https://docs.orchardcore.net/en/main/reference/modules/Placements/";
```suggestion
            var docsLink = "https://docs.orchardcore.net/en/main/reference/modules/Placements/";

```

2024-11-02 08:54 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Templates/Controllers/TemplateController.cs
> +            var placementsLink = Url.ActionLink("Index", "Admin", new { area = "OrchardCore.Placements" });
Can we rid off the magic string and use the action, controller names from the helpers

2024-11-02 11:31 UTC, hishamco approved these changes

2024-11-05 19:40 UTC, Piedone commented
Can this be merged, or are you waiting for anything, @hishamco? If it can, please merge.

2024-11-05 19:49 UTC, merged

2024-11-05 20:12 UTC, sebastienros commented
Modules should not reference modules. To remove the dependency use a route name. And if the module/feature is not enabled it could create an issue, so maybe check it first. Or just point to the documentation.

2024-11-05 20:17 UTC, hishamco commented
Oops, I didn't notice that because the path did not contain `Modules`, let me revise this again and remove the module reference