AssignRoleToUsers should not be implied by EditUsers
OrchardCMS/OrchardCore pull request #16954
Opened 2024-11-05 21:35 UTC by hishamco

Fixes #16756

2024-11-05 23:25 UTC, MikeAlhayek commented
@hishamco the issue is tagged with 3.0. It is probably better to work on these issues when we are getting ready to release 3.0 to avoid conflicts and extra work

2024-11-05 23:40 UTC, hishamco commented
To be honest I'm not sure what is the roadmap, I think we should make this clear to everyone on the team

2024-11-06 05:08 UTC, MikeAlhayek commented
The issue is assigned to 3.0 milestones. That means it won't be merged in 2.x.

2024-11-06 10:52 UTC, hishamco commented
I changed it to `2.1.0`

2024-11-06 14:16 UTC, MikeAlhayek commented
You can't change it. It's a breaking change. That's why it was tagged with 3.0.

2024-11-06 15:56 UTC, MikeAlhayek commented
its not a bug and has been like this for a long time. But we should not need that EditUsers permissions there.

2024-11-21 20:28 UTC, MikeAlhayek commented
@hishamco please document this change into 3.0.0 release notes and we'll merge it.

2024-11-24 00:25 UTC, MikeAlhayek requested changes
Please use descriptive docs in the release notes to help users understand what happened and what they should do to maintain behavior.

2024-11-24 00:25 UTC, MikeAlhayek commented on src/docs/releases/3.0.0.md
> +The `AssignRoleToUsers` permission should not be implied by `EditUsers`.
```suggestion
The `AssignRoleToUsers` permission is no longer implicitly granted by `EditUsers`. To maintain the same behavior, make sure to explicitly assign the `AssignRoleToUsers` permission to any role that already has the `EditUsers` permission.
```

2024-11-25 06:10 UTC, merged