Add PollingTime & MinimumIdelTime to BackgroundServiceOptions
OrchardCMS/OrchardCore pull request #17034
Opened 2024-11-18 16:21 UTC by hishamco

Fixes #17031

2024-11-18 20:19 UTC, hishamco commented on src/OrchardCore/OrchardCore.Abstractions/Modules/BackgroundServiceOptions.cs
> +    public int PollingTime { get; set; } = 60;
Ok, for that we need to make things consistent across the code base

2024-11-19 00:11 UTC, Piedone requested changes
Please add a note about this to the release notes.

2024-11-19 00:11 UTC, Piedone commented on src/OrchardCore.Cms.Web/appsettings.json
> +    //  "PollingTime": "00:01:00",
```suggestion
    // The polling time for the background tasks, i.e. how much to wait between executing all the background tasks of a given tenant.
    //  "PollingTime": "00:01:00",
```

2024-11-19 00:11 UTC, Piedone commented on src/OrchardCore/OrchardCore.Abstractions/Modules/BackgroundServiceOptions.cs
> +    /// Gets or sets the polling time for the background task.
```suggestion
    /// Gets or sets the polling time for the background tasks, i.e. how much to wait between executing all the background tasks of a given tenant.
```

2024-11-19 00:11 UTC, Piedone commented on src/OrchardCore/OrchardCore.Abstractions/Modules/BackgroundServiceOptions.cs
> +    /// Gets or set the minimum idle time before the background task is triggered.
```suggestion
    /// Gets or sets the minimum idle time before the background tasks of a tenant are triggered, similar to <see cref="PollingTime" />.
```

2024-11-19 00:11 UTC, Piedone commented on src/OrchardCore.Cms.Web/appsettings.json
> +    //  "MinimumIdelTime": "00:00:10"
```suggestion
    // The minimum idle time before the background tasks of a tenant are triggered, similar to PollingTime.
    //  "MinimumIdelTime": "00:00:10"
```

2024-11-19 00:11 UTC, Piedone commented on src/OrchardCore/OrchardCore.Abstractions/Modules/BackgroundServiceOptions.cs
> +    public TimeSpan MinimumIdelTime { get; set; } = TimeSpan.FromSeconds(10);
```suggestion
    public TimeSpan MinimumIdleTime { get; set; } = TimeSpan.FromSeconds(10);
```

2024-11-19 00:17 UTC, hishamco commented on src/OrchardCore/OrchardCore/Modules/ModularBackgroundService.cs
> +                await Task.Delay(_options.MinimumIdelTime, stoppingToken);
```suggestion
                await Task.Delay(_options.MinimumIdleTime, stoppingToken);
```

2024-11-19 00:26 UTC, hishamco commented on src/OrchardCore/OrchardCore/Modules/ModularBackgroundService.cs
> +            await Task.Delay(_options.MinimumIdelTime, stoppingToken);
```suggestion
            await Task.Delay(_options.MinimumIdleTime, stoppingToken);
```

2024-11-19 00:31 UTC, Piedone requested changes
Note I updated the previous code suggestions a bit ago.

2024-11-19 00:31 UTC, Piedone commented on src/OrchardCore/OrchardCore.Abstractions/Modules/BackgroundServiceOptions.cs
> +    /// Gets or sets the minimum idle time before the background tasks of a tenant are triggered, similar to <see cref="PollingTime" />.
```suggestion
    /// Gets or sets the minimum idle time before the background tasks of a tenant are triggered, as well as between tasks similar to <see cref="PollingTime" />.
```

2024-11-19 00:31 UTC, Piedone commented on src/OrchardCore.Cms.Web/appsettings.json
> +    // The minimum idle time before the background tasks of a tenant are triggered, similar to PollingTime.
```suggestion
    // The minimum idle time before the background tasks of a tenant are triggered, as well as between tasks similar to PollingTime.
```

2024-11-19 00:32 UTC, Piedone commented on src/OrchardCore.Cms.Web/appsettings.json
>      //  "MinimumIdelTime": "00:00:10"
```suggestion
    //  "MinimumIdleTime": "00:00:10"
```

2024-11-19 00:34 UTC, hishamco commented
Working from mobile is a hard, I will check it tomorrow from with my laptop

2024-11-19 15:14 UTC, Piedone approved these changes

2024-11-19 15:35 UTC, merged