OrchardHelper content APIs should be accessible without namespace
OrchardCMS/OrchardCore pull request #17189
Opened 2024-12-09 10:03 UTC by hishamco

All `IOrchardHelper` extension methods are easily accessible without a namespace in RazorPages or MVC views, except Content APIs this PR make them consistent with others

2024-12-17 13:24 UTC, gvkries commented
I agree with this, but it's again a breaking change.

2024-12-23 19:16 UTC, ns8482e commented
Please don't change namespace, instead update module/theme templates to include `OrchardCore` as global using

2024-12-23 23:12 UTC, hishamco commented
Which module do you mean? But the change is necessary to make things consistent, `3.0.0` is the only way to accept such breaking change

2025-02-21 08:13 UTC, gvkries commented
Moving the helper class out of the module, as done in PR #17414, should be done at the same time.

2025-02-21 09:56 UTC, hishamco commented
Do you mean out of `OC.Contents`? If yes this mean we should revise the other helpers coz I'm sure that I saw some inside the module projects

If the intend is to avoid module reference once we use them. I might create another PR after to make things consistent

2025-03-15 12:54 UTC, gvkries requested changes
Sorry @hishamco, forgot about this PR.

I'm not sure about the new location of the extensions. In the PR #17414 it was moved to `OrchardCore.ContentManagement`, which was agreed upon during triage. You've now moved it to `OrchardCore.Contents.Core` instead.
I think maybe the best location would be in `OrchardCore.ContentManagement.Display`, where we have other extensions for Razor anyway.

2025-03-18 00:53 UTC, hishamco commented
Frankly I don't know how the other PR will fix the issue

2025-03-18 09:07 UTC, gvkries commented
> Frankly, I don't know how the other PR will fix the issue

The other PR moves the same class to another project. Both changes are related, but not the same. Doing both changes at once makes sense, but moving the class to a different project here and then again to another one doesn't make sense.

2025-03-27 17:59 UTC, sebastienros approved these changes

2025-03-27 18:00 UTC, gvkries approved these changes

2025-03-27 18:18 UTC, merged