Show ThemeToggler on supported themes only
OrchardCMS/OrchardCore pull request #17243
Opened 2024-12-14 18:13 UTC by MikeAlhayek

The Theme toggler (Dark/Auto/Light) should be explicitly added to themes that support it. By default it should not be added to every frontend theme.

2024-12-14 22:16 UTC, Piedone requested changes
Was this causing any issues? Since nothing was displayed e.g. under TheBlog theme. Because if not, it would be easier to just permanently display it in `Detail`, as it was (but not `DetailAdmin`), rather than reimplementing the driver in every theme where we need it.

2024-12-14 22:16 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.Themes/Drivers/ToggleThemeNavbarDisplayDriver.cs
Shouldn't this rather be in `TheAdmin`? Also, there are three `ToggleTheme.cshtml`s, and two scripts this doesn't seem right: Either the feature is reasonable reusable, and then we shouldn't have slightly different copies of the driver and template, or it's not, but then there shouldn't be anything the Themes module.

There's the toggler JS that seems reusable (and indeed reused) at least.

2024-12-14 22:39 UTC, MikeAlhayek commented
It is showing up on every theme that uses the NavBar which is wrong because not every theme supports theme toggle. So we should not by default expose it since the default implementation is for Bootstrap 5.3 only

If someone designs a bs5.3 theme and wants to support theme toggle, they should add the toggler using a driver. But we should not just display it always. 

The issue that I ran into is that I am creating a theme that does not need toggler, but the toggler is showing up for me. Not something we should do

2024-12-15 19:57 UTC, Piedone commented
OK, I see.

2024-12-17 00:58 UTC, MikeAlhayek commented on src/OrchardCore.Modules/OrchardCore.Themes/Drivers/ToggleThemeNavbarDisplayDriver.cs
@Piedone 
When I developed this, I made it reusable for any BS 5.3 theme. However, not all BS 5.3-based themes require a toggler, even though BS 5.3 itself supports themes. The `ToggleThemeNavbarDisplayDriver` driver can be relocated to `TheAdmin`, and we can also move `ToggleTheme.DetailAdmin.cshtml`. However, the `ToggleTheme.cshtml` file should remain in the Themes directory to maintain its reusability. This ensures that users who are using BS 5.3 and want the default toggle implementation can still access it without issues along with `theme-manager` script which is needed for the toggler to work.

2024-12-17 01:28 UTC, Piedone commented on src/OrchardCore.Modules/OrchardCore.Themes/Drivers/ToggleThemeNavbarDisplayDriver.cs
OK!

2024-12-18 13:32 UTC, MikeAlhayek commented
@Piedone anything else to add here or should we merge it?

2024-12-18 14:10 UTC, Piedone commented
See https://discord.com/channels/551136772243980291/1246954405014671513/1317165890181140560 I'll review soon.

2024-12-18 23:18 UTC, Piedone approved these changes

2024-12-18 23:24 UTC, merged