Set max width on activity/task span
OrchardCMS/OrchardCore pull request #6031
Opened 2020-04-24 12:45 UTC by duncanhoggan

Just some style updates to the activity block to prevent them from becoming super long (as seen below)

![image](https://user-images.githubusercontent.com/6050438/80213779-fc289f80-8639-11ea-8206-818673c8e564.png)

Now it looks like this 

![image](https://user-images.githubusercontent.com/6050438/80213922-3c881d80-863a-11ea-9428-ff63d379de5a.png)

2020-04-24 17:57 UTC, deanmarcussen commented
Does this need a rebuild of the gulp file for the wwwroot/css file, as the only update here is to the sass?

2020-04-24 19:20 UTC, duncanhoggan commented
Happy to do the build, I assumed the CI/CD would handle that. Will run the tasks and get the css and minified css included👍

2020-04-25 12:51 UTC, Skrypt commented on src/OrchardCore.Modules/OrchardCore.Workflows/Assets/Styles/workflow-canvas.scss
> +            max-width: 300px;
It doesn't prevent the box itself to not become too wide by doing this. I can find other type of activities/events that are not using span at all.

2020-04-25 12:51 UTC, Skrypt commented on src/OrchardCore.Modules/OrchardCore.Workflows/Assets/Styles/workflow-canvas.scss
> +            max-width: 300px;
Example : 

![image](https://user-images.githubusercontent.com/3228637/80280428-faaab600-86d1-11ea-9198-05e18af70e31.png)

2020-04-25 16:42 UTC, deanmarcussen commented
> I assumed the CI/CD would handle that. 

Just for info, when you change the sass, you have to build the css. The CI can't do that, because we need the generated css in the git repository, for everyone using it :)

2020-04-28 06:23 UTC, duncanhoggan commented
@Skrypt hmm, yeah I was solving a very specific issue there, I'll update the PR to be more generic.
@deanmarcussen Thanks for the heads up, I'll make sure to get all the styles pre-compiled 👍.

2020-09-17 08:44 UTC, agriffard commented
Please merge form dev and rebuild the assets with gulp

2020-10-28 17:45 UTC, Skrypt requested changes
Use a more global class selector.

2020-10-28 17:45 UTC, Skrypt commented on src/OrchardCore.Modules/OrchardCore.Workflows/Assets/Styles/workflow-canvas.scss
> +            display: inline-block;
It doesn't prevent the box itself to not become too wide by doing this. I can find other type of activities/events that are not using span at all.

![80280428-faaab600-86d1-11ea-9198-05e18af70e31](https://user-images.githubusercontent.com/3228637/97475559-ca173380-1923-11eb-9d72-27dc64078bc4.png)

2020-12-17 09:18 UTC, agriffard commented
Closing the dontmerge labels.

2020-12-17 09:18 UTC, closed without merging