Make deployment plans unique
OrchardCMS/OrchardCore pull request #6804
Opened 2020-08-01 17:16 UTC by deanmarcussen

Fixes https://github.com/OrchardCMS/OrchardCore/issues/6774

2020-08-27 22:20 UTC, hishamco requested changes
LGTM after we ignore the casing

2020-08-27 22:20 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Deployment/Controllers/DeploymentPlanController.cs
> +                    var count = await _session.QueryIndex<DeploymentPlanIndex>(x => x.Name == model.Name && x.DocumentId != model.Id).CountAsync();
Please use `.Equals()` with ignore casing

2020-08-28 08:19 UTC, deanmarcussen commented on src/OrchardCore.Modules/OrchardCore.Deployment/Controllers/DeploymentPlanController.cs
> +                    var count = await _session.QueryIndex<DeploymentPlanIndex>(x => x.Name == model.Name && x.DocumentId != model.Id).CountAsync();
Yeah makes sense. Done

2020-08-28 08:21 UTC, agriffard commented
Build error: 
`DeploymentPlanController.cs(286,69): error CS1503: Argument 3: cannot convert from 'System.StringComparer' to 'System.StringComparison'`

2020-08-28 08:36 UTC, agriffard commented
Test run is still failing after the change.

2020-08-28 09:28 UTC, merged