Features documentation
OrchardCMS/OrchardCore pull request #6942
Opened 2020-08-20 09:13 UTC by agriffard

List all the features in a new tab of the documentation, organized by group.
Ex: Core, Content, Admin, Design, Extensibility.

2020-08-20 09:27 UTC, agriffard commented
https://docs.orchardcore.net/en/ag-features/docs/features/core/

Each feature should have a small description and a 'See more' line if available somewhere else in the documentation.

We can also add a screenshot if we can find a good image that represents the feature.

Each group should not have too many features (the right TOC should not have to be scrolled to see all the links).
If they are too many, they should be splitted in different groups.

2020-12-26 00:08 UTC, Piedone commented
Sorry for taking so much time, I'll review this and https://github.com/OrchardCMS/OrchardCore/pull/7997 soon.

2020-12-26 16:50 UTC, Piedone requested changes

2020-12-26 16:50 UTC, Piedone commented on src/docs/features/README.md
> +# Features
I'm not sure I understand the goal with this new section. Isn't it largely overlapping with the Glossary and Reference sections?

Maybe the Reference section could get a landing page (now it just opens the first page, Content Types) that explains something along the lines of:

```
This is a comprehensive reference for the modules and their features available in Orchard Core. Under each of these pages, you'll find an overview of the given module with documentation on how to use and extend them.
```

But I think providing a categorization of the features based on their areas of function, or goals a user may want to achieve with them is great. So probably also have a similar TOC there as under the "Sections" title here below, and list all related features under the bullet points, linking to their reference pages?

And all the one-sentence summaries under each feature here could be moved to the reference pages, if something like this is missing for the given module.

If you agree, I can create a PR for this.

2020-12-26 17:05 UTC, agriffard commented
I just want that people get an overview of which features are available.
I am not sure of what is the best way.

The references stick to the structure of the projects and each project/module can have many features so I tried to organize them like the admin sections.

2020-12-26 17:08 UTC, agriffard commented
In the end, I want something that is exhaustive (list all current features) and that we keep maintained when we add new features (and may be announce them when planned in milestones).

2020-12-26 17:09 UTC, Piedone commented
Yeah, I see that but I don't think it's good to have a third section where people can basically get an overview of what's in the platform (also thinking about these getting out of sync over time).

Right now, this new section is a categorized list of features. But we already have an up to date list of features, so I'd just categorize that (with a TOC that provides a different approach than the structure of the solution folders). And if further documentation is warranted for each module (feature) I'd also continue to add it there.

2020-12-28 14:14 UTC, agriffard commented
The features page is not really up to date: https://docs.orchardcore.net/en/dev/docs/reference/modules/Features/
It should be in another page with links to doc page if available.
The version of OC is not really essential.

2020-12-29 00:47 UTC, Piedone commented
I don't really see the value of having that page you linked to begin with and it's not really part of OrchardCore.Features either. All in all, I'd still do what I suggested above.

2020-12-29 11:24 UTC, agriffard commented
Ok, please do as you suggest @Piedone.

2020-12-29 11:24 UTC, closed without merging