Move feeds to feature
OrchardCMS/OrchardCore pull request #7313
Opened 2020-10-19 03:28 UTC by ns8482e

Move feeds to feature

2020-10-19 07:08 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Lists/Startup.cs
> +
Just remove the two extra lines

2020-10-19 07:09 UTC, hishamco approved these changes
LGTM

2020-10-19 07:24 UTC, deanmarcussen requested changes
Good, yes, but I need to check it is non breaking.

Please hold off on merging for a little bit

2020-10-19 07:26 UTC, hishamco commented
Sure, I need to try this too ;)

2020-10-19 12:43 UTC, deanmarcussen commented
Ok, so it's non breaking which is good.

But I think the comment actually meant to move the `ListPart` feeds provider to an actual feature, so that one could have feeds, without lists being a provider of feeds.

i.e. still providing custom feeds from other sources.

but better change than nothing, so ok with me.

Niraj if you wanted to move it to an actual feature, it would just need to enable the feature by default in a migration on Lists (to be non breaking)

2020-10-19 18:35 UTC, ns8482e commented
I changed to hide the following UI for users when `OrchardCore.Feeds` is disabled as it's returning `404`.

![image](https://user-images.githubusercontent.com/23270244/96496700-2fc23c00-120f-11eb-9855-b158bc7027a2.png)

The change in this PR will only display FeedUrl options when when `OrchardCore.Feeds` is enabled.

2020-10-20 09:42 UTC, deanmarcussen approved these changes

2020-10-20 09:46 UTC, merged