Only use email in ResetPasword
OrchardCMS/OrchardCore pull request #7613
Opened 2020-11-13 12:05 UTC by agriffard

Fixes #7540

2020-11-13 14:10 UTC, rjpowers10 reviewed
I'm not sure this completely resolves #7540 

`UserService.GetForgotPasswordUserAsync` has the same problem. Seems to me like `UserService.FindByUsernameOrEmailAsync` is just a flawed method and needs to be removed. `GetForgotPasswordUserAsync` would also call `UserManager.FindByEmail`.

2020-11-13 14:10 UTC, rjpowers10 commented on src/OrchardCore/OrchardCore.Users.Core/Services/UserService.cs
> +            var user = await _userManager.FindByEmailAsync(userIdentifier) as User;
Should userIdentifier be renamed to email? I believe there is also a check above that says "A user name or email is required.", which isn't accurate anymore.

2020-11-13 17:18 UTC, rjpowers10 reviewed
Sorry, I think there are a few last pieces.

- [ForgotPassword.cshtml](https://github.com/OrchardCMS/OrchardCore/blob/c953909cf9cb399df78fd2eb1cff21d28dfe11ff/src/OrchardCore.Modules/OrchardCore.Users/Views/ResetPassword/ForgotPassword.cshtml#L15) still says "Email or username"
- Might want to update [ForgotPasswordViewModel](https://github.com/OrchardCMS/OrchardCore/blob/c953909cf9cb399df78fd2eb1cff21d28dfe11ff/src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ForgotPasswordViewModel.cs#L8) similar to [ResetPasswordViewModel](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ResetPasswordViewModel.cs) in that it prompts for and validates the email.

Thank you for taking this!

2020-11-14 13:10 UTC, hishamco requested changes

2020-11-14 13:10 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ForgotPasswordViewModel.cs
> +            else if (Email.IndexOf('@') == -1 || !MailboxAddress.TryParse(Email, out var emailAddress))
We already have `IEmailAddressValidator` on Infrastructure APIs that could be used here

2020-11-20 13:23 UTC, merged