Support multiple translation providers
OrchardCMS/OrchardCore pull request #8940
Opened 2021-03-22 05:03 UTC by doticca

Adds support to LocalizationManager for multiple translation providers. #8939

2021-03-22 05:03 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=8940) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=8940) before we can accept your contribution.<br/><br/>:x: doticca [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=8940)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=8940) it.</sub>

2021-03-22 18:27 UTC, Skrypt commented
Related with https://github.com/OrchardCMS/OrchardCore/pull/8098

2021-05-08 01:04 UTC, hishamco requested changes
LGTM except the little comment

2021-05-08 01:04 UTC, hishamco commented on src/OrchardCore/OrchardCore.Localization.Core/LocalizationManager.cs
> +                foreach (var translationProvider in this._translationProviders)
Just remove `this`

2021-05-10 08:34 UTC, merged

2021-05-10 16:24 UTC, Skrypt commented
Ok, I just analyzed this and it makes sense. Now we have the PoFilesTranslationsProvider and DataTranslationsProvider as ITranslationProviders. They are 2 different providers so that they return different localizations results. Basically, you should never use `T["Something"]` to provide a Content Type/Dynamic data name translation but `D["Something"]`. If we would have only one ITranslationProvider it would probably merge translations together in the same IDictionary.