User Registration - Option for required confirm password
OrchardCMS/OrchardCore pull request #9572
Opened 2021-05-28 10:23 UTC by XpandIT-RFID

fixes #9566

This adds a flag to Registration Settings that allows the backoffice to choose if they want a Confirm Password field in the Registration.

2021-05-28 10:23 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=9572) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=9572) before we can accept your contribution.<br/><br/>:x: XpandIT-RFID [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=9572)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=9572) it.</sub>

2021-06-03 17:30 UTC, sebastienros commented on src/OrchardCore.Modules/OrchardCore.Users/ViewModels/RegisterViewModel.cs
>          public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
Please make this method async. And change the call stack accordingly.

2021-06-03 17:30 UTC, sebastienros commented on src/OrchardCore.Modules/OrchardCore.Users/Views/Registration/Register.cshtml
> +@inject OrchardCore.Settings.ISiteService _siteService;
Can you move it up, before the block that calls it?

2021-06-04 10:29 UTC, hishamco requested changes

2021-06-04 10:29 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Users/ViewModels/RegisterViewModel.cs
> +
Remove extra lines and apply Sebastien suggestions

2021-06-04 10:29 UTC, hishamco commented on src/OrchardCore.Modules/OrchardCore.Users/ViewModels/RegisterViewModel.cs
> +
Remove extra lines and apply Sebastien suggestions

2022-08-12 01:53 UTC, CrestApps commented
Fix conflicts

2022-08-13 08:52 UTC, hishamco commented
@XpandIT-RFID could you please address the feedback to finish this PR

2024-01-16 00:54 UTC, Piedone commented
Closing due to no reply from the author.

2024-01-16 00:54 UTC, closed without merging